In [30]:
import numpy as np
import pandas as pd

## 2017-2018 school vaccination data
- Numbers in the original document have been surpressed for <=1%, <=2%, <=5% and >=95%,>=98%,>=99%. Original file has errors with <=,  >=, and --* symbols when importing directly from .xlsx
- The 3 raw datafiles for childcare, kindergarden, and 7th grade has been compiled manually into a csv called `raw17_18_combined.csv` with <= and >= removed and replaced with the corresponding numbers

In [31]:
# Import raw combined 2017-2018 school vaccination data
pertusis_1718 = pd.read_csv("Raw_Data/raw17_18_combined.csv",encoding = "ISO-8859-1")

In [32]:
pertusis_1718.head()

,FACILITY_NUMBER,COUNTY,pub_priv_headstart,CITY,FACILITY_NAME,ENROLLMENT,n,pct,vac_info_type,REPORTED
0,10214883,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . ANGELA AGUILAR CENTER,63.0,.,98,childcare,Y
1,13417425,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . SUE MATHESON CENTER,47.0,.,95,childcare,Y
2,13420593,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START. COLLEGE OF ALAMEDA HEAD START,44.0,.,95,childcare,Y
3,13417441,ALAMEDA,PRIVATE,ALAMEDA,SUGAR AND SPICE,NaN,.,.,childcare,N
4,6151211,ALAMEDA,PRIVATE,ALAMEDA,MCKINNEY CHRISTIAN ACADEMY,NaN,.,.,kindergarten,N

In [23]:
#Clean up missing values and set to Nan
pertusis_1718.n=pertusis_1718.n.replace('.', np.nan)
pertusis_1718.pct=pertusis_1718.pct.replace('.',np.nan)

# uppercase all counties and cities
pertusis_1718.COUNTY=pertusis_1718['COUNTY'].str.upper()
pertusis_1718.CITY=pertusis_1718['CITY'].str.upper()

In [24]:
pertusis_1718.dtypes

FACILITY_NUMBER         int64
COUNTY                 object
pub_priv_headstart     object
CITY                   object
FACILITY_NAME          object
ENROLLMENT            float64
n                      object
pct                    object
vac_info_type          object
REPORTED               object
dtype: object

In [25]:
# Change n and percent to floats
pertusis_1718[['n', 'pct']] = pertusis_1718[['n', 'pct']].astype('float64')

In [26]:
# Check conversion
pertusis_1718.dtypes

FACILITY_NUMBER         int64
COUNTY                 object
pub_priv_headstart     object
CITY                   object
FACILITY_NAME          object
ENROLLMENT            float64
n                     float64
pct                   float64
vac_info_type          object
REPORTED               object
dtype: object

In [27]:
pertusis_1718.head()

,FACILITY_NUMBER,COUNTY,pub_priv_headstart,CITY,FACILITY_NAME,ENROLLMENT,n,pct,vac_info_type,REPORTED
0,10214883,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . ANGELA AGUILAR CENTER,63.0,NaN,98.0,childcare,Y
1,13417425,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . SUE MATHESON CENTER,47.0,NaN,95.0,childcare,Y
2,13420593,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START. COLLEGE OF ALAMEDA HEAD START,44.0,NaN,95.0,childcare,Y
3,13417441,ALAMEDA,PRIVATE,ALAMEDA,SUGAR AND SPICE,NaN,NaN,NaN,childcare,N
4,6151211,ALAMEDA,PRIVATE,ALAMEDA,MCKINNEY CHRISTIAN ACADEMY,NaN,NaN,NaN,kindergarten,N

In [9]:
sum(pertusis_1718.REPORTED=='N')

1005

In [10]:
sum(pertusis_1718.REPORTED=='Y')

18304

Subset dataset to those that reported

In [11]:
# Take subset that have numbers
vac_1718=pertusis_1718[pertusis_1718.REPORTED=='Y']

In [12]:
vac_1718.head()

,FACILITY_NUMBER,COUNTY,pub_priv_headstart,CITY,FACILITY_NAME,ENROLLMENT,n,pct,vac_info_type,REPORTED
0,10214883,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . ANGELA AGUILAR CENTER,63.0,NaN,98.0,childcare,Y
1,13417425,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . SUE MATHESON CENTER,47.0,NaN,95.0,childcare,Y
2,13420593,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START. COLLEGE OF ALAMEDA HEAD START,44.0,NaN,95.0,childcare,Y
6,13415928,ALAMEDA,PRIVATE,ALAMEDA,BRIGHT HORIZONS AT GARNER,109.0,NaN,99.0,childcare,Y
7,13419403,ALAMEDA,PRIVATE,ALAMEDA,PETER PAN SCHOOL,100.0,NaN,99.0,childcare,Y

Numbers in the original document have been surpressed for <=1%, <=2%, <=5% and >=95%,>=98%,>=99% so will impute values by assuming that the percentage is equal to whatever value listed and multiply by the number of students enrolled at the school.

In [13]:
# Calculate n from enrollment and approximate percentage
vac_1718.loc[:,('n')]=vac_1718.n.fillna(vac_1718.ENROLLMENT*vac_1718.pct/100)

C:\Users\42\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [14]:
vac_1718.head()

,FACILITY_NUMBER,COUNTY,pub_priv_headstart,CITY,FACILITY_NAME,ENROLLMENT,n,pct,vac_info_type,REPORTED
0,10214883,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . ANGELA AGUILAR CENTER,63.0,61.74,98.0,childcare,Y
1,13417425,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . SUE MATHESON CENTER,47.0,44.65,95.0,childcare,Y
2,13420593,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START. COLLEGE OF ALAMEDA HEAD START,44.0,41.80,95.0,childcare,Y
6,13415928,ALAMEDA,PRIVATE,ALAMEDA,BRIGHT HORIZONS AT GARNER,109.0,107.91,99.0,childcare,Y
7,13419403,ALAMEDA,PRIVATE,ALAMEDA,PETER PAN SCHOOL,100.0,99.00,99.0,childcare,Y

In [15]:
# Change to integers 
vac_1718.loc[:,('ENROLLMENT','n','pct')]=vac_1718.loc[:,('ENROLLMENT','n','pct')].astype('int64')

C:\Users\42\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [16]:
vac_1718.head()

,FACILITY_NUMBER,COUNTY,pub_priv_headstart,CITY,FACILITY_NAME,ENROLLMENT,n,pct,vac_info_type,REPORTED
0,10214883,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . ANGELA AGUILAR CENTER,63,61,98,childcare,Y
1,13417425,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . SUE MATHESON CENTER,47,44,95,childcare,Y
2,13420593,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START. COLLEGE OF ALAMEDA HEAD START,44,41,95,childcare,Y
6,13415928,ALAMEDA,PRIVATE,ALAMEDA,BRIGHT HORIZONS AT GARNER,109,107,99,childcare,Y
7,13419403,ALAMEDA,PRIVATE,ALAMEDA,PETER PAN SCHOOL,100,99,99,childcare,Y

In [17]:
# Change print settings to see all
#np.set_printoptions(threshold=np.nan)
#change back to default printing length
np.set_printoptions(threshold=5)
# Check County names
sorted(list(vac_1718.COUNTY.unique()))

['ALAMEDA',
 'AMADOR',
 'BUTTE',
 'CALAVERAS',
 'COLUSA',
 'CONTRA COSTA',
 'DEL NORTE',
 'EL DORADO',
 'FRESNO',
 'GLENN',
 'HUMBOLDT',
 'IMPERIAL',
 'INYO',
 'KERN',
 'KINGS',
 'LAKE',
 'LASSEN',
 'LOS ANGELES',
 'MADERA',
 'MARIN',
 'MARIPOSA',
 'MENDOCINO',
 'MERCED',
 'MODOC',
 'MONO',
 'MONTEREY',
 'NAPA',
 'NEVADA',
 'ORANGE',
 'PLACER',
 'PLUMAS',
 'RIVERSIDE',
 'SACRAMENTO',
 'SAN BENITO',
 'SAN BERNARDINO',
 'SAN DIEGO',
 'SAN FRANCISCO',
 'SAN JOAQUIN',
 'SAN LUIS OBISPO',
 'SAN MATEO',
 'SANTA BARBARA',
 'SANTA CLARA',
 'SANTA CRUZ',
 'SHASTA',
 'SIERRA',
 'SISKIYOU',
 'SOLANO',
 'SONOMA',
 'STANISLAUS',
 'SUTTER',
 'TEHAMA',
 'TRINITY',
 'TULARE',
 'TUOLUMNE',
 'VENTURA',
 'YOLO',
 'YUBA']

In [18]:
#Check city names
sorted(list(vac_1718.CITY.unique()))

['ACAMPO',
 'ACTON',
 'ACTON, CA',
 'ADELANTO',
 'AGOURA',
 'AGOURA HILLS',
 'AGUANGA',
 'AHWAHNEE',
 'ALAMEDA',
 'ALAMO',
 'ALBANY',
 'ALHAMBRA',
 'ALISO VIEJO',
 'ALPAUGH',
 'ALPINE',
 'ALTA LOMA',
 'ALTADENA',
 'ALTURAS',
 'ALVISO',
 'AMERICAN CANYON',
 'ANAHEIM',
 'ANAHEIM HILLS',
 'ANAHEIM,',
 'ANANHEIM',
 'ANDERSON',
 'ANGELS CAMP',
 'ANTELOPE',
 'ANTIOCH',
 'ANZA',
 'APPLE VALLEY',
 'APTOS',
 'ARBOGA',
 'ARBUCKLE',
 'ARCADIA',
 'ARCATA',
 'ARLETA',
 'ARMONA',
 'ARNOLD',
 'AROMAS',
 'ARROYO GRANDE',
 'ARTESIA',
 'ARVIN',
 'ATASCADERO',
 'ATHERTON',
 'ATWATER',
 'AUBERRY',
 'AUBURN',
 'AVALON',
 'AVENAL',
 'AVERY',
 'AZUSA',
 'BAKERSFIELD',
 'BALDWIN PARK',
 'BALLICO',
 'BANNING',
 'BANTA',
 'BARSTOW',
 'BAY POINT',
 'BAYSIDE',
 'BEALE AFB',
 'BEALE AIR FORCE BASE',
 'BEAUMONT',
 'BELL',
 'BELL GARDENS',
 'BELLA VISTA',
 'BELLFLOWER',
 'BELMONT',
 'BELVEDERE',
 'BENICA',
 'BENICIA',
 'BERKELEY',
 'BERMUDA DUNES',
 'BEVERLY HILLS',
 'BIG BEAR CITY',
 'BIG BEAR LAKE',
 'BIGGS',
 'BISHOP',
 'BLOOMINGTON',
 'BLUE LAKE',
 'BLYTHE',
 'BOLINAS',
 'BONITA',
 'BONSALL',
 'BOONVILLE',
 'BORON',
 'BORREGO SPRINGS',
 'BOULDER CREEK',
 'BOULEVARD',
 'BOYES HOT SPRINGS',
 'BRADBURY',
 'BRAWLEY',
 'BREA',
 'BRENTWOOD',
 'BRICELAND',
 'BRISBANE',
 'BROWNS VALLEY',
 'BUELLTON',
 'BUENA PARK',
 'BURBANK',
 'BURLINGAME',
 'BURNEY',
 'BUTTONWILLOW',
 'BYRON',
 'CA',
 'CABAZON',
 'CALABASAS',
 'CALEXICO',
 'CALIFORNIA CITY',
 'CALIMESA',
 'CALIPATRIA',
 'CALISTOGA',
 'CALPELLA',
 'CAMARILLO',
 'CAMBRIA',
 'CAMERON PARK',
 'CAMINO',
 'CAMPBELL',
 'CAMPO',
 'CANOGA PARK',
 'CANTUA CREEK',
 'CANYON COUNTRY',
 'CANYON LAKE',
 'CAPISTRANO BEACH',
 'CAPITOLA',
 'CARDIFF',
 'CARDIFF BY THE SEA',
 'CARLOTTA',
 'CARLSBAD',
 'CARMEL',
 'CARMEL VALLEY',
 'CARMICHAEL',
 'CARPINTERIA',
 'CARSON',
 'CARUTHERS',
 'CASTAIC',
 'CASTRO VALLEY',
 'CASTROVILLE',
 'CATHEDRAL CITY',
 'CATHEYS VALLEY',
 'CAYUCOS',
 'CERES',
 'CERRITOS',
 'CHALLENGE',
 'CHATSWORTH',
 'CHERRY VALLEY',
 'CHESTER',
 'CHICO',
 'CHINO',
 'CHINO HILLS',
 'CHINO,',
 'CHOWCHILLA',
 'CHUALAR',
 'CHULA VISTA',
 'CHULAR',
 'CITRUS HEIGHTS',
 'CITY OF COMMERCE',
 'CITY OF INDUSTRY',
 'CLAREMONT',
 'CLARKSBURG',
 'CLAYTON',
 'CLEARLAKE',
 'CLEARLAKE OAKS',
 'CLOVERDALE',
 'CLOVIS',
 'COACHELLA',
 'COALINGA',
 'COARSEGOLD',
 'COLEVILLE',
 'COLFAX',
 'COLMA',
 'COLTON',
 'COLUMBIA',
 'COLUSA',
 'COMMERCE',
 'COMPTON',
 'CONCORD',
 'COOL',
 'COPPEROPOLIS',
 'CORCORAN',
 'CORNING',
 'CORONA',
 'CORONA DEL MAR',
 'CORONADO',
 'CORTE MADERA',
 'COSTA MESA',
 'COSTA MESA,',
 'COTATI',
 'COTO DE CAZA',
 'COTTONWOOD',
 'COURTLAND',
 'COVELO',
 'COVINA',
 'CRESCENT CITY',
 'CRESSEY',
 'CREST PARK',
 'CRESTLINE',
 'CROCKETT',
 'CUDAHAY',
 'CUDAHY',
 'CULVER CITY',
 'CUPERTINO',
 'CUTLER',
 'CYPRESS',
 'DALY CITY',
 'DANA POINT',
 'DANVILLE',
 'DAVENPORT',
 'DAVIS',
 'DEL MAR',
 'DEL REY',
 'DEL REY OAKS',
 'DELANO',
 'DELHI',
 'DENAIR',
 'DESCANSO',
 'DESERT HOT SPRINGS',
 'DIAMOND BAR',
 'DIAMOND SPRINGS',
 'DINUBA',
 'DISCOVERY BAY',
 'DIXON',
 'DORRIS',
 'DOS PALOS',
 'DOUGLAS CITY',
 'DOWNEY',
 'DUARTE',
 'DUBLIN',
 'DUCOR',
 'DUNLAP',
 'DURHAM',
 'E. NICOLAUS',
 'E. RANCHO DOMINGUEZ',
 'E. WHITTIER',
 'EARLIMART',
 'EAST NICOLAUS',
 'EAST PALO ALTO',
 'EASTVALE',
 'EDWARDS',
 'EL CAJON',
 'EL CENTRO',
 'EL CERRITO',
 'EL DORADO HILLS',
 'EL GRANADA',
 'EL MONTE',
 'EL SEGUNDO',
 'EL SEGUNDO,',
 'EL SOBRANTE',
 'ELK GROVE',
 'ELVERTA',
 'EMERALD HILLS',
 'EMERYVILLE',
 'EMPIRE',
 'ENCINITAS',
 'ENCINO',
 'ESCALON',
 'ESCONDIDO',
 'ESPARTO',
 'ETIWANDA',
 'ETNA',
 'EUREKA',
 'EXETER',
 'FAIR OAKS',
 'FAIRFAX',
 'FAIRFIELD',
 'FAIRIFELD',
 'FALL RIVER MILLS',
 'FALLBROOK',
 'FARMERSVILLE',
 'FELTON',
 'FERNDALE',
 'FILLMORE',
 'FIREBAUGH',
 'FIVE POINTS',
 'FOLSOM',
 'FONTANA',
 'FOOTHILL RANCH',
 'FORESTHILL',
 'FORESTVILLE',
 'FORT BRAGG',
 'FORT IRWIN',
 'FORT JONES',
 'FORTUNA',
 'FOSTER CITY',
 'FOUNTAIN VALLEY',
 'FOWLER',
 'FRAZIER PARK',
 'FREEDOM',
 'FREMONT',
 'FREMOTN',
 'FRENCH CAMP',
 'FRESNO',
 'FT. IRWIN',
 'FULLERTON',
 'GALT',
 'GARDEN GROVE',
 'GARDEN VALLEY',
 'GARDENA',
 'GEORGETOWN',
 'GERBER',
 'GEYSERVILLE',
 'GILROY',
 'GLEN ELLEN',
 'GLENDALE',
 'GLENDORA',
 'GOLD RIVER',
 'GOLETA',
 'GONZALES',
 'GRANADA HILLS',
 'GRAND TERRACE',
 'GRANITE BAY',
 'GRASS VALLEY',
 'GREENFIELD',
 'GREENFILED',
 'GRENADA',
 'GRIDLEY',
 'GROVELAND',
 'GROVER BEACH',
 'GUADALUPE',
 'GUERNEVILLE',
 'GUSTINE',
 'HACIENDA HEIGHTS',
 'HALF MOON BAY',
 'HAMILTON CITY',
 'HANFORD',
 'HAPPY CAMP',
 'HARBOR CITY',
 'HAWAIIAN GARDENS',
 'HAWTHORNE',
 'HAYWARD',
 'HEALDSBURG',
 'HEBER',
 'HELENDALE',
 'HEMET',
 'HERALD',
 'HERCULES',
 'HERMOSA BEACH',
 'HESPERIA',
 'HICKMAN',
 'HIGHLAND',
 'HIGHLAND PARK',
 'HILLSBOROUGH',
 'HILMAR',
 'HOLLISTER',
 'HOLLYWOOD',
 'HOLTVILLE',
 'HOOPA',
 'HUGHSON',
 'HUNTINGTON',
 'HUNTINGTON BEACH',
 'HUNTINGTON PARK',
 'HURON',
 'HYDESVILLE',
 'IDYLLWILD',
 'IMPERIAL',
 'IMPERIAL BEACH',
 'INDIAN WELLS',
 'INDIO',
 'INGLEWOOD',
 'INYOKERN',
 'IONE',
 'IRVINE',
 'ISLETON',
 'IVANHOE',
 'JACKSON',
 'JAMESTOWN',
 'JAMUAL',
 'JAMUL',
 'JANESVILLE',
 'JOSHUA TREE',
 'JULIAN',
 'JURUPA VALLEY',
 'KELSEYVILLE',
 'KENSINGTON',
 'KENTFIELD',
 'KENWOOD',
 'KERMAN',
 'KERNVILLE',
 'KETTLEMAN CITY',
 'KEYES',
 'KING CITY',
 'KINGS BEACH',
 'KINGSBURG',
 'KNIGHTS FERRY',
 'KNIGHTS LANDING',
 'KNIGHTSEN',
 'LA',
 'LA CANADA',
 'LA CANADA FLINTRIDGE',
 'LA CRESCENTA',
 'LA GRANGE',
 'LA HABRA',
 'LA HABRA HEIGHTS',
 'LA JOLLA',
 'LA MESA',
 'LA MIRADA',
 'LA PALMA',
 'LA PUENTE',
 'LA QUINTA',
 'LA SELVA BEACH',
 'LA VERNE',
 'LADERA RANCH',
 'LAFAYETTE',
 'LAGUNA BEACH',
 'LAGUNA HILLS',
 'LAGUNA NIGUEL',
 'LAGUNA WOODS',
 'LAKE ARROWHEAD',
 'LAKE BALBOA',
 'LAKE ELSINORE',
 'LAKE FOREST',
 'LAKE HUGHES',
 'LAKE ISABELLA',
 'LAKE VIEW TERRACE',
 'LAKE VIEW TERRANCE',
 'LAKEPORT',
 'LAKESIDE',
 'LAKEVIEW TERRACE',
 'LAKEWOOD',
 'LAMONT',
 'LANCASTER',
 'LANCASTER,',
 'LARKSPUR',
 'LATHROP',
 'LATON',
 'LAVERNE',
 'LAWNDALE',
 'LAYTONVILLE',
 'LE GRAND',
 'LEBEC',
 'LEMON COVE',
 'LEMON GROVE',
 'LEMOORE',
 'LENNOX',
 'LENWOOD',
 'LEUCADIA',
 'LINCOLN',
 'LINDEN',
 'LINDSAY',
 'LITTLEROCK',
 'LIVE OAK',
 'LIVERMORE',
 'LIVINGSTON',
 'LOCKEFORD',
 'LOCKWOOD',
 'LODI',
 'LOMA LINDA',
 'LOMITA',
 'LOMPOC',
 'LONE PINE',
 'LONG BEACH',
 'LOOMIS',
 'LOS ALAMITOS',
 'LOS ALAMOS',
 'LOS ALTOS',
 'LOS ALTOS HILLS',
 'LOS ANGELES',
 'LOS BANOS',
 'LOS FLORES',
 'LOS GATOS',
 'LOS MOLINOS',
 'LOS NIETOS',
 'LOS OLIVOS',
 'LOS OSOS',
 'LOST HILLS',
 'LOWER LAKE',
 'LOYALTON',
 'LUCERNE',
 'LUCERNE VALLEY',
 'LYNWOOD',
 'MADERA',
 'MADISON',
 'MAGALIA',
 'MALIBU',
 'MAMMOTH LAKES',
 'MANHATTAN BEACH',
 'MANTECA',
 'MAR VISTA',
 'MARICOPA',
 'MARIN CITY',
 'MARINA',
 'MARINA DEL REY',
 'MARIPOSA',
 'MARTINEZ',
 'MARYSVILLE',
 'MATHER',
 'MAXWELL',
 'MAYWOOD',
 'MC KINLEYVILLE',
 'MCARTHUR',
 'MCCLELLAN',
 'MCFARLAND',
 'MCKINLEYVILLE',
 'MEADOW VISTA',
 'MECCA',
 'MENDOCINO',
 'MENDOTA',
 'MENIFEE',
 'MENLO PARK',
 'MENTONE',
 'MERCED',
 'MERIDIAN',
 'MIDDLETOWN',
 'MIDWAY CITY',
 'MILL VALLEY',
 'MILLBRAE',
 'MILLVILLE',
 'MILPITAS',
 'MIRA LOMA',
 'MIRANDA',
 'MISSION HILLS',
 'MISSION VIEJO',
 'MODESTO',
 'MOFFETT FIELD',
 'MOJAVE',
 'MONROVIA',
 'MONTAGUE',
 'MONTARA',
 'MONTCLAIR',
 'MONTEBELLO',
 'MONTEREY',
 'MONTEREY PARK',
 'MONTROSE',
 'MOORPARK',
 'MORAGA',
 'MORENO VALLEY',
 'MORGAN HILL',
 'MORONGO VALLEY',
 'MORRO BAY',
 'MOUNT HERMON',
 'MOUNT SHASTA',
 'MOUNTAIN HOUSE',
 'MOUNTAIN VIEW',
 'MT. SHASTA',
 'MURPHYS',
 'MURRIETA',
 'MURRIETTA',
 'N. HOLLYWOOD',
 'N.A.S. LEMOORE',
 'NAPA',
 'NAS LEMOORE',
 'NATIONAL CITY',
 'NEEDLES',
 'NEVADA CITY',
 'NEW CUYAMA',
 'NEWARK',
 'NEWBERRY SPRINGS',
 'NEWBURY PARK',
 'NEWCASTLE',
 'NEWHALL',
 'NEWMAN',
 'NEWPORT BEACH',
 'NEWPORT BEACH,',
 'NIPOMO',
 'NORCO',
 'NORTH FORK',
 'NORTH HIGHLANDS',
 'NORTH HILLS',
 'NORTH HOLLYWOOD',
 'NORTH SHORE',
 'NORTH TUSTIN',
 'NORTHRIDGE',
 'NORWALK',
 'NOVATO',
 'NUEVO',
 "O'NEALS",
 'OAK HILLS',
 'OAK PARK',
 'OAK VIEW',
 'OAKDALE',
 'OAKHURST',
 'OAKLAND',
 'OAKLEY',
 'OCCIDENTAL',
 'OCEANO',
 'OCEANSIDE',
 'OJAI',
 'OLIVEHURST',
 'OLYMPIC VALLEY',
 'ONTARIO',
 'ORANGE',
 'ORANGE COVE',
 'ORANGEVALE',
 'ORCUTT',
 'ORINDA',
 'ORLAND',
 'ORO GRANDE',
 'OROSI',
 'OROVILLE',
 'OXNARD',
 'PACIFIC GROVE',
 'PACIFIC PALISADES',
 'PACIFICA',
 'PACOIMA',
 'PACOMIA',
 'PALERMO',
 'PALM DESERT',
 'PALM SPRINGS',
 'PALMDALE',
 'PALO ALTO',
 'PALO CEDRO',
 'PALOS VERDES',
 'PALOS VERDES ESTATES',
 'PALOS VERDES PENINSULA',
 'PANORAM CITY',
 'PANORAMA CITY',
 'PARADISE',
 'PARAMOUNT',
 'PARLIER',
 'PASADENA',
 'PASO ROBLES',
 'PATTERSON',
 'PAUMA VALLEY',
 'PEARBLOSSOM',
 'PENN VALLEY',
 'PENNGROVE',
 'PENRYN',
 'PERRIS',
 'PESCADERO',
 'PETALUMA',
 'PETROLIA',
 'PHELAN',
 'PICO RIVERA',
 'PIEDMONT',
 'PINE VALLEY',
 'PINEDALE',
 'PINOLE',
 'PINON HILLS',
 'PIONEER',
 'PIRU',
 'PISMO BEACH',
 'PITTSBURG',
 'PIXLEY',
 'PLACENTIA',
 'PLACERVILLE',
 'PLANADA',
 'PLAYA DEL REY',
 'PLAYA VISTA',
 'PLEASANT GROVE',
 'PLEASANT HILL',
 'PLEASANTON',
 'PLUMAS LAKE',
 'PLYMOUTH',
 'POINT ARENA',
 'POINT REYES STATION',
 'POLLOCK PINES',
 'POMONA',
 'PORT HUENEME',
 'PORTER RANCH',
 'PORTERVILLE',
 'PORTOLA',
 'PORTOLA VALLEY',
 'POTRERO',
 'POTTER VALLEY',
 'POWAY',
 'PRATHER',
 'PRUNEDALE',
 'PT. REYES STATION',
 'QUAIL VALLEY',
 'QUARTZ HILL',
 'QUINCY',
 'RAINBOW',
 'RAISIN CITY',
 'RAMONA',
 'RANCHO CORDOVA',
 'RANCHO CUCAMONGA',
 'RANCHO DOMINGUEZ',
 'RANCHO MIRAGE',
 'RANCHO MURIETA',
 'RANCHO PALOS VERDES',
 'RANCHO SAN MARGARITA',
 'RANCHO SANTA FE',
 'RANCHO SANTA MARGARI',
 'RANCHO SANTA MARGARITA',
 'RANCHO STA MARGAITA',
 'RANCHO STA MARGARITA',
 'RANCHOS PALOS VERDES',
 'RCHO STA MARG',
 'RED BLUFF',
 'REDDING',
 'REDLANDS',
 'REDONDO BEACH',
 'REDWAY',
 'REDWOOD CITY',
 'REDWOOD VALLEY',
 'REEDLEY',
 'RESCUE',
 'RESEDA',
 'RIALTO',
 'RICHGROVE',
 'RICHMOND',
 'RIDGECREST',
 'RIM FOREST',
 'RIO DELL',
 'RIO LINDA',
 'RIO VISTA',
 'RIPON',
 'RIVERBANK',
 'RIVERDALE',
 'RIVERSIDE',
 'RIVERSIDE,',
 'ROCKLIN',
 'RODEO',
 'ROHNERT PARK',
 'ROLLING HILLS ESTATE',
 'ROLLING HILLS ESTATES',
 'ROMOLAND',
 'ROSAMOND',
 'ROSEMEAD',
 'ROSEVILLE',
 'ROSS',
 'ROSSMOOR',
 'ROWLAND HEIGHTS',
 'ROYAL OAKS',
 'RUNNING SPRINGS',
 'RUTHERFORD',
 'S. EL MONTE',
 'S. LAKE TAHOE',
 'SACRAMENTO',
 'SALIDA',
 'SALINAS',
 'SALTON CITY',
 'SAN ANDREAS',
 'SAN ANSELMO',
 'SAN BERARDINO',
 'SAN BERNARDINO',
 'SAN BRUNO',
 'SAN CARLOS',
 'SAN CLEMENTE',
 'SAN DIEGO',
 'SAN DIMAS',
 'SAN FERNANDO',
 'SAN FRANCISCO',
 'SAN FRNCISCO',
 'SAN GABRIEL',
 'SAN GERONIMO',
 'SAN JACINTO',
 'SAN JOAQUIN',
 'SAN JOSE',
 'SAN JOSE,',
 'SAN JUAN BAUTISTA',
 'SAN JUAN CAPISTRANO',
 'SAN LEANDRO',
 'SAN LORENZO',
 'SAN LUIS OBISPO',
 'SAN MARCOS',
 'SAN MARINO',
 'SAN MARTIN',
 'SAN MATEO',
 'SAN MIGUEL',
 'SAN PABLO',
 'SAN PEDRO',
 'SAN RAFAEL',
 'SAN RAMON',
 'SAN YSIDRO',
 'SANGER',
 'SANTA ANA',
 'SANTA BARARA',
 'SANTA BARBARA',
 'SANTA CATALINA',
 'SANTA CLARA',
 'SANTA CLARITA',
 'SANTA CRUZ',
 'SANTA FE SPRINGS',
 'SANTA MARGARITA',
 'SANTA MARIA',
 'SANTA MONICA',
 'SANTA NELLA',
 'SANTA PAULA',
 'SANTA ROSA',
 'SANTA YNEZ',
 'SANTEE',
 'SARATOGA',
 'SAUGUS',
 'SAUSALITO',
 'SCOTTS VALLEY',
 'SEAL BEACH',
 'SEASIDE',
 'SEBASTOPOL',
 'SEELEY',
 'SELMA',
 'SEPULVEDA',
 'SHAFTER',
 'SHANDON',
 'SHASTA',
 'SHASTA LAKE',
 'SHASTA LAKE CITY',
 'SHERMAN OAKS',
 'SHINGLE SPRINGS',
 'SHINGLETOWN',
 'SIERRA MADRE',
 'SIGNAL HILL',
 'SILVERADO',
 'SILVERADO CANYON',
 'SIMI VALLEY',
 'SLOUGHHOUSE',
 'SMITH RIVER',
 'SOLANA BEACH',
 'SOLEDAD',
 'SOLVANG',
 'SOMERSET',
 'SOMIS',
 'SONOMA',
 'SONORA',
 'SOQUEL',
 'SOULSBYVILLE',
 'SOUTH EL MONTE',
 'SOUTH GATE',
 'SOUTH LAKE TAHOE',
 'SOUTH LATE TAHOE',
 'SOUTH PASADENA',
 'SOUTH SAN FRANCISCO',
 'SOUTH SAN GABRIEL',
 'SOUTH WHITTIER',
 'SPRECKELS',
 'SPRECKLES',
 'SPRING VALLEY',
 'SPRINGVILLE',
 'ST. HELENA',
 'STANFORD',
 'STANTON',
 'STEVENSON RANCH',
 'STEVENSONS RANCH',
 'STEVINSON',
 'STOCKTON',
 'STRATFORD',
 'STRATHMORE',
 'STUDIO CITY',
 'SUISUN',
 'SUISUN CITY',
 'SUN CITY',
 'SUN VALLEY',
 'SUNLAND',
 'SUNNYALE',
 'SUNNYVALE',
 'SUNOL',
 'SUNSET BEACH',
 'SUPELVEDA',
 'SUSANVILLE',
 'SUTTER',
 'SUTTER CREEK',
 'SYLMAR',
 'TAFT',
 'TAHOE CITY',
 'TARZANA',
 'TEHACHAPI',
 'TEHAMA',
 'TEMECULA',
 'TEMPLE CITY',
 'TEMPLETON',
 'TERRA BELLA',
 'THERMAL',
 'THORNTON',
 'THOUSAND OAKS',
 'THOUSAND PALMS',
 'THREE RIVERS',
 'TIBURON',
 'TIPTON',
 'TOLLHOUSE',
 'TOMALES',
 'TOPANGA',
 'TORRANCE',
 'TRABUCO CANYON',
 'TRACY',
 'TRANQUILLITY',
 'TRAVER',
 'TRAVIS AFB',
 'TRINIDAD',
 'TRONA',
 'TRUCKEE',
 'TUJUNGA',
 'TULARE',
 'TULELAKE',
 'TUOLUMNE',
 'TUPMAN',
 'TURLOCK',
 'TURLOCK,',
 'TUSTIN',
 'TWAIN HARTE',
 'TWENTY NINE PALMS',
 'TWENTYNINE PALMS',
 'TWIN PEAKS',
 'UKIAH',
 'UNION CITY',
 'UPLAND',
 'UPPER LAKE',
 'UPPERLAKE',
 'VACAVILLE',
 'VALENCIA',
 'VALINDA',
 'VALLEJO',
 'VALLEY CENTER',
 'VALLEY GLEN',
 'VALLEY SPRINGS',
 'VALLEY VILLAGE',
 'VAN NUYS',
 'VANDENBERG AFB',
 'VANDENBERG AIR FORCE BASE',
 'VENICE',
 'VENTURA',
 'VICTOR',
 'VICTORVILLE',
 'VILLA PARK',
 'VISALIA',
 'VISTA',
 'W. SACRAMENTO',
 'WALNUT',
 'WALNUT CREEK',
 'WALNUT CREET',
 'WALNUT GROVE',
 'WALNUT PARK',
 'WALNUT VALLEY',
 'WARNER SPRINGS',
 'WASCO',
 'WATERFORD',
 'WATSONVILLE',
 'WEAVERVILLE',
 'WEED',
 'WEIMAR',
 'WELDON',
 'WEST COVINA',
 'WEST HILLS',
 'WEST HOLLYWOOD',
 'WEST SACRAMENTO',
 'WESTCHESTER',
 'WESTLAKE VILLAGE',
 'WESTLEY',
 'WESTMINISTER',
 'WESTMINSTER',
 'WESTMORLAND',
 'WHEATLAND',
 'WHITMORE',
 'WHITTIER',
 'WILDOMAR',
 'WILLIAMS',
 'WILLITS',
 'WILLOW CREEK',
 'WILLOWS',
 'WILMINGTON',
 'WILTON',
 'WINCHESTER',
 'WINDSOR',
 'WINNETKA',
 'WINTERHAVEN',
 'WINTERS',
 'WINTON',
 'WOODLAKE',
 'WOODLAND',
 'WOODLAND HILLS',
 'WOODSIDE',
 'WRIGHTWOOD',
 'YERMO',
 'YORBA LINDA',
 'YOUNTVILLE',
 'YREKA',
 'YUBA CITY',
 'YUCAIPA',
 'YUCCA VALLEY']

In [19]:
# Fix City Typos
vac_1718.loc[vac_1718.CITY=='ACTON, CA', 'CITY']='ACTON'
vac_1718.loc[vac_1718.CITY=='AGOURA', 'CITY']='AGOURA HILLS'
vac_1718.loc[vac_1718.CITY=='ANAHEIM,', 'CITY']='ANAHEIM'
vac_1718.loc[vac_1718.CITY=='ANANHEIM,', 'CITY']='ANAHEIM'
vac_1718.loc[vac_1718.CITY=='CA', 'CITY']='NAPA'
vac_1718.loc[vac_1718.CITY=='BEALE AIR FORCE BASE', 'CITY']='BEALE AFB' # to match census name
vac_1718.loc[vac_1718.CITY=='BENICA', 'CITY']='BENICIA'
vac_1718.loc[vac_1718.CITY=='CARDIFF', 'CITY']='CARDIFF BY THE SEA'
vac_1718.loc[vac_1718.CITY=='CARMEL', 'CITY']='CARMEL VALLEY'
vac_1718.loc[vac_1718.CITY=='CHINO,', 'CITY']='CHINO'
vac_1718.loc[vac_1718.CITY=='CHULAR', 'CITY']='CHUALAR'
vac_1718.loc[vac_1718.CITY=='CITY OF COMMERCE', 'CITY']='COMMERCE'
vac_1718.loc[vac_1718.CITY=='CITY OF INDUSTRY', 'CITY']='INDUSTRY'
vac_1718.loc[vac_1718.CITY=='CUDAHAY', 'CITY']='CUDAHY'
vac_1718.loc[vac_1718.CITY=='E. NICOLAUS', 'CITY']='EAST NICOLAUS'
vac_1718.loc[vac_1718.CITY=='E. RANCHO DOMINGUEZ', 'CITY']='EAST RANCHO DOMINGUEZ'
vac_1718.loc[vac_1718.CITY=='E. WHITTIER', 'CITY']='EAST WHITTIER'
vac_1718.loc[vac_1718.CITY=='EL SEGUNDO,', 'CITY']='EL SEGUNDO'
vac_1718.loc[vac_1718.CITY=='FAIRIFELD', 'CITY']='FAIRFIELD'
vac_1718.loc[vac_1718.CITY=='FREMOTN', 'CITY']='FREMONT'
vac_1718.loc[vac_1718.CITY=='FT. IRWIN', 'CITY']='FORT IRWIN'
vac_1718.loc[vac_1718.CITY=='GREENFILED', 'CITY']='GREENFIELD'
vac_1718.loc[vac_1718.CITY=='HUNTINGTON', 'CITY']='HUNTINGTON PARK'
vac_1718.loc[vac_1718.CITY=='JAMUAL', 'CITY']='JAMUL'
vac_1718.loc[vac_1718.CITY=='LA', 'CITY']='LOS ANGELES'
vac_1718.loc[vac_1718.CITY=='LA CANADA', 'CITY']='LA CANADA FLINTRIDGE'
vac_1718.loc[vac_1718.CITY=='LAKE VIEW TERRANCE', 'CITY']='LAKE VIEW TERRACE'
vac_1718.loc[vac_1718.CITY=='LAKEVIEW TERRACE', 'CITY']='LAKE VIEW TERRACE'
vac_1718.loc[vac_1718.CITY=='LANCASTER,', 'CITY']='LANCASTER'
vac_1718.loc[vac_1718.CITY=='LAVERNE', 'CITY']='LA VERNE'
vac_1718.loc[vac_1718.CITY=='MC KINLEYVILLE', 'CITY']='MCKINLEYVILLE'
vac_1718.loc[vac_1718.CITY=='MONTROSE', 'CITY']='LA CRESCENTA-MONTROSE'
vac_1718.loc[vac_1718.CITY=='MT. SHASTA', 'CITY']='MOUNT SHASTA'
vac_1718.loc[vac_1718.CITY=='N. HOLLYWOOD', 'CITY']='NORTH HOLLYWOOD'
vac_1718.loc[vac_1718.CITY=='N.A.S. LEMOORE', 'CITY']='LEMOORE STATION' # match census
vac_1718.loc[vac_1718.CITY=='NAS LEMOORE', 'CITY']='LEMOORE STATION'
vac_1718.loc[vac_1718.CITY=='NEWPORT BEACH,', 'CITY']='NEWPORT BEACH'
vac_1718.loc[vac_1718.CITY=='PACOMIA', 'CITY']='PACOIMA'
vac_1718.loc[vac_1718.CITY=='PANORAM ', 'CITY']='PANORAMA CITY'
vac_1718.loc[vac_1718.CITY=='PT. REYES STATION', 'CITY']='POINT REYES STATION'
vac_1718.loc[vac_1718.CITY=='RANCHO SANTA MARGARI', 'CITY']='RANCHO SANTA MARGARITA'
vac_1718.loc[vac_1718.CITY=='RANCHO SAN MARGARITA', 'CITY']='RANCHO SANTA MARGARITA'
vac_1718.loc[vac_1718.CITY=='RANCHO STA MARGAITA', 'CITY']='RANCHO SANTA MARGARITA'
vac_1718.loc[vac_1718.CITY=='RANCHO STA MARGARITA', 'CITY']='RANCHO SANTA MARGARITA'
vac_1718.loc[vac_1718.CITY=='RCHO STA MARG', 'CITY']='RANCHO SANTA MARGARITA'
vac_1718.loc[vac_1718.CITY=='RANCHOS PALOS VERDES', 'CITY']='RANCHO PALOS VERDES'
vac_1718.loc[vac_1718.CITY=='RIVERSIDE,', 'CITY']='RIVERSIDE'
vac_1718.loc[vac_1718.CITY=='ROLLING HILLS ESTATE', 'CITY']='ROLLING HILLS ESTATES'
vac_1718.loc[vac_1718.CITY=='S. EL MONTE', 'CITY']='SOUTH EL MONTE'
vac_1718.loc[vac_1718.CITY=='S. LAKE TAHOE', 'CITY']='SOUTH LAKE TAHOE'
vac_1718.loc[vac_1718.CITY=='SAN BERARDINO', 'CITY']='SAN BERNARDINO'
vac_1718.loc[vac_1718.CITY=='SAN FRNCISCO', 'CITY']='SAN FRANCISCO'
vac_1718.loc[vac_1718.CITY=='SAN JOSE,', 'CITY']='SAN JOSE'
vac_1718.loc[vac_1718.CITY=='SANTA BARARA', 'CITY']='SANTA BARBARA'
vac_1718.loc[vac_1718.CITY=='SHASTA LAKE CITY', 'CITY']='SHASTA LAKE'
vac_1718.loc[vac_1718.CITY=='SILVERADO CANYON', 'CITY']='SILVERADO'
vac_1718.loc[vac_1718.CITY=='SOUTH LATE TAHOE', 'CITY']='SOUTH LAKE TAHOE'
vac_1718.loc[vac_1718.CITY=='SPRECKLES', 'CITY']='SPRECKELS'
vac_1718.loc[vac_1718.CITY=='STEVENSONS RANCH', 'CITY']='STEVENSON RANCH'
vac_1718.loc[vac_1718.CITY=='SUISUN', 'CITY']='SUISUN CITY'
vac_1718.loc[vac_1718.CITY=='SUNNYALE', 'CITY']='SUNNYVALE'
vac_1718.loc[vac_1718.CITY=='SUPELVEDA', 'CITY']='SEPULVEDA'
vac_1718.loc[vac_1718.CITY=='TURLOCK,', 'CITY']='TURLOCK'
vac_1718.loc[vac_1718.CITY=='UPPERLAKE', 'CITY']='UPPER LAKE'
vac_1718.loc[vac_1718.CITY=='VANDENBERG AIR FORCE BASE', 'CITY']='VANDENBERG AFB' # match census
vac_1718.loc[vac_1718.CITY=='W. SACRAMENTO', 'CITY']='WEST SACRAMENTO'

C:\Users\42\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [20]:
#Double check city names
#sorted(list(vac_1718.CITY.unique()))

In [21]:
#Get count of students vaccinated by county,city and grade
vac_n=vac_1718.groupby(by=['COUNTY','CITY','vac_info_type'])['n'].sum()
vac_n

COUNTY   CITY             vac_info_type
ALAMEDA  ALAMEDA          7th grade         931
                          childcare        1231
                          kindergarten      986
         ALBANY           7th grade         255
                          childcare         249
                          kindergarten      307
         BERKELEY         7th grade         908
                          childcare        2346
                          kindergarten      860
         CASTRO VALLEY    7th grade         776
                          childcare         797
                          kindergarten      864
         DUBLIN           7th grade         939
                          childcare        1275
                          kindergarten     1150
         EMERYVILLE       7th grade          50
                          childcare         238
                          kindergarten       70
         FREMONT          7th grade        2855
                          childcare        4388
                          kindergarten     3743
         HAYWARD          7th grade        1803
                          childcare        1852
                          kindergarten     2101
         LIVERMORE        7th grade        1047
                          childcare        1439
                          kindergarten     1331
         NEWARK           7th grade         514
                          childcare        1015
                          kindergarten      673
                                           ...
YOLO     ESPARTO          childcare          41
                          kindergarten       60
         KNIGHTS LANDING  kindergarten       57
         MADISON          childcare          39
         WEST SACRAMENTO  7th grade         655
                          childcare         415
                          kindergarten      817
         WINTERS          7th grade         133
                          childcare         176
                          kindergarten      127
         WOODLAND         7th grade         799
                          childcare         928
                          kindergarten      867
YUBA     ARBOGA           childcare          61
         BEALE AFB        childcare          62
                          kindergarten      124
         BROWNS VALLEY    kindergarten       22
         CHALLENGE        kindergarten       23
         MARYSVILLE       7th grade         409
                          childcare         352
                          kindergarten      402
         OLIVEHURST       7th grade         406
                          childcare         221
                          kindergarten      404
         PLUMAS LAKE      7th grade         150
                          childcare          53
                          kindergarten      177
         WHEATLAND        7th grade         139
                          childcare          99
                          kindergarten       90
Name: n, Length: 2334, dtype: int64

In [22]:
#Export count of students vaccinated by county,city and grade
vac_n.to_csv("vac_n_table1718.csv", index=False)

In [23]:
#Get average percentage of students vaccinated by county,city and grade
vac_pct=vac_1718.groupby(by=['COUNTY','CITY','vac_info_type'])['pct'].mean()
vac_pct

COUNTY   CITY             vac_info_type
ALAMEDA  ALAMEDA          7th grade        94.900000
                          childcare        96.000000
                          kindergarten     96.384615
         ALBANY           7th grade        98.000000
                          childcare        95.571429
                          kindergarten     97.666667
         BERKELEY         7th grade        96.750000
                          childcare        92.750000
                          kindergarten     91.333333
         CASTRO VALLEY    7th grade        97.000000
                          childcare        89.384615
                          kindergarten     97.416667
         DUBLIN           7th grade        97.200000
                          childcare        92.857143
                          kindergarten     97.800000
         EMERYVILLE       7th grade        96.000000
                          childcare        96.000000
                          kindergarten     98.000000
         FREMONT          7th grade        96.000000
                          childcare        96.196970
                          kindergarten     97.538462
         HAYWARD          7th grade        97.272727
                          childcare        95.742857
                          kindergarten     97.214286
         LIVERMORE        7th grade        96.125000
                          childcare        96.416667
                          kindergarten     96.928571
         NEWARK           7th grade        97.333333
                          childcare        96.611111
                          kindergarten     96.800000
                                             ...
YOLO     ESPARTO          childcare        95.000000
                          kindergarten     97.000000
         KNIGHTS LANDING  kindergarten     97.000000
         MADISON          childcare        95.000000
         WEST SACRAMENTO  7th grade        96.444444
                          childcare        96.142857
                          kindergarten     87.666667
         WINTERS          7th grade        99.000000
                          childcare        95.750000
                          kindergarten     99.000000
         WOODLAND         7th grade        97.666667
                          childcare        95.904762
                          kindergarten     97.454545
YUBA     ARBOGA           childcare        97.000000
         BEALE AFB        childcare        98.000000
                          kindergarten     97.000000
         BROWNS VALLEY    kindergarten     95.000000
         CHALLENGE        kindergarten     92.000000
         MARYSVILLE       7th grade        92.000000
                          childcare        94.571429
                          kindergarten     86.200000
         OLIVEHURST       7th grade        97.000000
                          childcare        94.000000
                          kindergarten     92.600000
         PLUMAS LAKE      7th grade        99.000000
                          childcare        95.000000
                          kindergarten     98.000000
         WHEATLAND        7th grade        99.000000
                          childcare        96.500000
                          kindergarten     98.000000
Name: pct, Length: 2334, dtype: float64

In [24]:
#Export average percentage of students vaccinated by county,city and grade
vac_pct.to_csv("vac_pct_table1718.csv", index=False)

In [25]:
vac_1718.head()

,FACILITY_NUMBER,COUNTY,pub_priv_headstart,CITY,FACILITY_NAME,ENROLLMENT,n,pct,vac_info_type,REPORTED
0,10214883,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . ANGELA AGUILAR CENTER,63,61,98,childcare,Y
1,13417425,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START . SUE MATHESON CENTER,47,44,95,childcare,Y
2,13420593,ALAMEDA,HEAD START,ALAMEDA,ALAMEDA HEAD START. COLLEGE OF ALAMEDA HEAD START,44,41,95,childcare,Y
6,13415928,ALAMEDA,PRIVATE,ALAMEDA,BRIGHT HORIZONS AT GARNER,109,107,99,childcare,Y
7,13419403,ALAMEDA,PRIVATE,ALAMEDA,PETER PAN SCHOOL,100,99,99,childcare,Y

In [26]:
#Export full cleaned data
vac_1718.to_csv("clean1718.csv", index=False)

## Census Data Cleaning

### Demographics

In [28]:
# Import and clean census data for basic demographics age gender race
census16 = pd.read_csv("Raw_Data/Census/ACS_16_demographic.csv",encoding = "ISO-8859-1",
                       header=[0],na_values=['-'],)

In [28]:
census16.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC02_VC03,HC03_VC03,HC04_VC03,HC01_VC04,HC02_VC04,HC03_VC04,...,HC03_VC108,HC04_VC108,HC01_VC109,HC02_VC109,HC03_VC109,HC04_VC109,HC01_VC110,HC02_VC110,HC03_VC110,HC04_VC110
0,1600000US0600135,600135,"Acalanes Ridge CDP, California",1000,338,1000,(X),409,146,40.9,...,695,(X),279,101,40.1,7.1,416,194,59.9,7.1
1,1600000US0600156,600156,"Acampo CDP, California",466,398,466,(X),291,277,62.4,...,466,(X),291,277,62.4,13.7,175,137,37.6,13.7
2,1600000US0600212,600212,"Acton CDP, California",7170,555,7170,(X),3776,318,52.7,...,5777,(X),3020,279,52.3,2.2,2757,199,47.7,2.2
3,1600000US0600296,600296,"Adelanto city, California",32311,35,32311,(X),16350,651,50.6,...,16322,(X),8399,706,51.5,2.4,7923,539,48.5,2.4
4,1600000US0600310,600310,"Adin CDP, California",155,91,155,(X),59,40,38.1,...,115,(X),52,33,45.2,15.8,63,35,54.8,15.8

In [29]:
demographic16 = census16[['GEO.id','GEO.id2','GEO.display-label',
                     'HC01_VC03',
                     'HC01_VC04','HC03_VC04',
                     'HC01_VC05','HC03_VC05',
                     'HC01_VC08','HC03_VC08',
                     'HC01_VC09','HC03_VC09',
                     'HC01_VC10','HC03_VC10',
                     'HC01_VC11','HC03_VC11',
                     'HC01_VC12','HC03_VC12',
                     'HC01_VC13','HC03_VC13',
                     'HC01_VC14','HC03_VC14',
                     'HC01_VC15','HC03_VC15',
                     'HC01_VC16','HC03_VC16',
                     'HC01_VC17','HC03_VC17',
                     'HC01_VC18','HC03_VC18',
                     'HC01_VC19','HC03_VC19',
                     'HC01_VC20','HC03_VC20',
                     'HC01_VC23','HC03_VC23',
                     'HC01_VC88','HC03_VC88',
                     'HC01_VC94','HC03_VC94',
                     'HC01_VC95','HC03_VC95',
                     'HC01_VC96','HC03_VC96',
                     'HC01_VC97','HC03_VC97',
                     'HC01_VC98','HC03_VC98',
                     'HC01_VC99','HC03_VC99',
                     'HC01_VC100','HC03_VC100',
                     'HC01_VC101','HC03_VC101',
                     'HC01_VC102','HC03_VC102'                 
        ]]

In [30]:
demographic16.dtypes

GEO.id                object
GEO.id2                int64
GEO.display-label     object
HC01_VC03              int64
HC01_VC04              int64
HC03_VC04            float64
HC01_VC05              int64
HC03_VC05            float64
HC01_VC08              int64
HC03_VC08            float64
HC01_VC09              int64
HC03_VC09            float64
HC01_VC10              int64
HC03_VC10            float64
HC01_VC11              int64
HC03_VC11            float64
HC01_VC12              int64
HC03_VC12            float64
HC01_VC13              int64
HC03_VC13            float64
HC01_VC14              int64
HC03_VC14            float64
HC01_VC15              int64
HC03_VC15            float64
HC01_VC16              int64
HC03_VC16            float64
HC01_VC17              int64
HC03_VC17            float64
HC01_VC18              int64
HC03_VC18            float64
HC01_VC19              int64
HC03_VC19            float64
HC01_VC20              int64
HC03_VC20            float64
HC01_VC23            float64
HC03_VC23             object
HC01_VC88              int64
HC03_VC88            float64
HC01_VC94              int64
HC03_VC94            float64
HC01_VC95              int64
HC03_VC95            float64
HC01_VC96              int64
HC03_VC96            float64
HC01_VC97              int64
HC03_VC97            float64
HC01_VC98              int64
HC03_VC98            float64
HC01_VC99              int64
HC03_VC99            float64
HC01_VC100             int64
HC03_VC100           float64
HC01_VC101             int64
HC03_VC101           float64
HC01_VC102             int64
HC03_VC102           float64
dtype: object

In [31]:
# demographic16[['HC01_VC03','HC01_VC04','HC01_VC05','HC01_VC08','HC01_VC09','HC01_VC10','HC01_VC11','HC01_VC12','HC01_VC13',
#           'HC01_VC14','HC01_VC15','HC01_VC16','HC01_VC17','HC01_VC18','HC01_VC19','HC01_VC20','HC01_VC23','HC01_VC88',
#           'HC01_VC94','HC01_VC95','HC01_VC96','HC01_VC97','HC01_VC98',
#           'HC01_VC99','HC01_VC100','HC01_VC101','HC01_VC102']] = demographic16[['HC01_VC03','HC01_VC04','HC01_VC05','HC01_VC08','HC01_VC09','HC01_VC10','HC01_VC11','HC01_VC12','HC01_VC13',
#           'HC01_VC14','HC01_VC15','HC01_VC16','HC01_VC17','HC01_VC18','HC01_VC19','HC01_VC20','HC01_VC23','HC01_VC88',
#           'HC01_VC94','HC01_VC95','HC01_VC96','HC01_VC97','HC01_VC98',
#           'HC01_VC99','HC01_VC100','HC01_VC101','HC01_VC102']].astype('float64')

In [32]:
#combine other race, two or more races (HC01_VC99, HC01_VC100, HC01_VC101, HC01_VC102)
demographic16['other']=pd.Series(census16['HC01_VC99']+census16['HC01_VC100']+census16['HC01_VC101']+census16['HC01_VC102'])

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [33]:
demographic16['other_pct']=pd.Series(census16['HC03_VC99']+census16['HC03_VC100']+census16['HC03_VC101']+census16['HC03_VC102'])

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
demographic16.rename(columns={'GEO.display-label': 'city',
                         'HC01_VC03': 'tot_pop', 
                         'HC01_VC04': 'male',
                         'HC01_VC05': 'female',
                         'HC01_VC08':'under_5',
                         'HC01_VC09':'5_9',
                         'HC01_VC10':'10_14',
                         'HC01_VC11':'15_19',
                         'HC01_VC12':'20_24',
                         'HC01_VC13':'25_34',
                         'HC01_VC14':'35_44',
                         'HC01_VC15':'45_54',
                         'HC01_VC16':'55_59',
                         'HC01_VC17':'60_64',
                         'HC01_VC18':'65_74',
                         'HC01_VC19':'75_84',
                         'HC01_VC20':'85_over',
                         'HC01_VC23':'median_age',
                         'HC01_VC88':'hispanic_latino',
                         'HC01_VC89':'mexican',
                         'HC01_VC94':'white',
                         'HC01_VC95':'black',
                         'HC01_VC96':'aian',
                         'HC01_VC97':'asian',
                         'HC01_VC98':'nhopi',

                         'HC03_VC04': 'male_pct',
                         'HC03_VC05': 'female_pct',
                         'HC03_VC08':'under_5_pct',
                         'HC03_VC09':'5_9_pct',
                         'HC03_VC10':'10_14_pct',
                         'HC03_VC11':'15_19_pct',
                         'HC03_VC12':'20_24_pct',
                         'HC03_VC13':'25_34_pct',
                         'HC03_VC14':'35_44_pct',
                         'HC03_VC15':'45_54_pct',
                         'HC03_VC16':'55_59_pct',
                         'HC03_VC17':'60_64_pct',
                         'HC03_VC18':'65_74_pct',
                         'HC03_VC19':'75_84_pct',
                         'HC03_VC20':'85_over_pct',
                         'HC03_VC23':'median_age_pct',
                         'HC03_VC88':'hispanic_latino_pct',
                         'HC03_VC89':'mexican_pct',
                         'HC03_VC94':'white_pct',
                         'HC03_VC95':'black_pct',
                         'HC03_VC96':'aian_pct',
                         'HC03_VC97':'asian_pct',
                         'HC03_VC98':'nhopi_pct'
                        }, 
                inplace=True)
# Other race categories
#                          'HC01_VC99':'other_only',
#                          'HC01_VC100':'more_two_races',
#                          'HC01_VC101':'more_two_races_other',
#                          'HC01_VC102':'more_two_races_other_exclude',

C:\Users\42\Anaconda3\lib\site-packages\pandas\core\frame.py:3778: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [35]:
demographic16.dtypes

GEO.id                  object
GEO.id2                  int64
city                    object
tot_pop                  int64
male                     int64
male_pct               float64
female                   int64
female_pct             float64
under_5                  int64
under_5_pct            float64
5_9                      int64
5_9_pct                float64
10_14                    int64
10_14_pct              float64
15_19                    int64
15_19_pct              float64
20_24                    int64
20_24_pct              float64
25_34                    int64
25_34_pct              float64
35_44                    int64
35_44_pct              float64
45_54                    int64
45_54_pct              float64
55_59                    int64
55_59_pct              float64
60_64                    int64
60_64_pct              float64
65_74                    int64
65_74_pct              float64
75_84                    int64
75_84_pct              float64
85_over                  int64
85_over_pct            float64
median_age             float64
median_age_pct          object
hispanic_latino          int64
hispanic_latino_pct    float64
white                    int64
white_pct              float64
black                    int64
black_pct              float64
aian                     int64
aian_pct               float64
asian                    int64
asian_pct              float64
nhopi                    int64
nhopi_pct              float64
HC01_VC99                int64
HC03_VC99              float64
HC01_VC100               int64
HC03_VC100             float64
HC01_VC101               int64
HC03_VC101             float64
HC01_VC102               int64
HC03_VC102             float64
other                    int64
other_pct              float64
dtype: object

In [36]:
demographic16['city']=demographic16.city.replace(' city, California', '', regex=True)

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
demographic16['city']=demographic16.city.replace(' CDP, California', '', regex=True)

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
demographic16['city']=demographic16.city.replace(' town, California', '', regex=True)

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [39]:
## Uppercase cities
demographic16['city']=demographic16['city'].str.upper()

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [40]:
demographic16=demographic16.drop(columns=['HC01_VC99','HC03_VC99','HC01_VC100','HC03_VC100','HC01_VC101','HC03_VC101','HC01_VC102','HC03_VC102'])
demographic16

,GEO.id,GEO.id2,city,tot_pop,male,male_pct,female,female_pct,under_5,under_5_pct,...,black,black_pct,aian,aian_pct,asian,asian_pct,nhopi,nhopi_pct,other,other_pct
0,1600000US0600135,600135,ACALANES RIDGE,1000,409,40.9,591,59.1,33,3.3,...,0,0.0,0,0.0,209,20.9,0,0.0,322,32.2
1,1600000US0600156,600156,ACAMPO,466,291,62.4,175,37.6,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,1600000US0600212,600212,ACTON,7170,3776,52.7,3394,47.3,350,4.9,...,120,1.7,15,0.2,67,0.9,0,0.0,254,3.6
3,1600000US0600296,600296,ADELANTO,32311,16350,50.6,15961,49.4,3148,9.7,...,5810,18.0,12,0.0,497,1.5,0,0.0,2061,6.3
4,1600000US0600310,600310,ADIN,155,59,38.1,96,61.9,7,4.5,...,0,0.0,0,0.0,0,0.0,0,0.0,10,6.4
5,1600000US0600394,600394,AGOURA HILLS,20689,10132,49.0,10557,51.0,910,4.4,...,313,1.5,10,0.0,1302,6.3,0,0.0,1014,4.8
6,1600000US0600450,600450,AGUA DULCE,3541,1814,51.2,1727,48.8,208,5.9,...,8,0.2,0,0.0,58,1.6,0,0.0,504,14.2
7,1600000US0600464,600464,AGUANGA,673,306,45.5,367,54.5,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
8,1600000US0600478,600478,AHWAHNEE,2225,1178,52.9,1047,47.1,101,4.5,...,0,0.0,32,1.4,0,0.0,0,0.0,26,1.2
9,1600000US0600535,600535,AIRPORT,1605,892,55.6,713,44.4,260,16.2,...,42,2.6,0,0.0,0,0.0,0,0.0,12,0.8
10,1600000US0600562,600562,ALAMEDA,77409,37708,48.7,39701,51.3,4586,5.9,...,5742,7.4,135,0.2,23552,30.4,550,0.7,9663,12.5
11,1600000US0600618,600618,ALAMO,16078,8394,52.2,7684,47.8,711,4.4,...,116,0.7,6,0.0,982,6.1,26,0.2,763,4.8
12,1600000US0600674,600674,ALBANY,19420,9400,48.4,10020,51.6,1500,7.7,...,740,3.8,63,0.3,5118,26.4,156,0.8,2641,13.6
13,1600000US0600716,600716,ALBION,227,106,46.7,121,53.3,0,0.0,...,2,0.9,0,0.0,46,20.3,0,0.0,50,22.0
14,1600000US0600786,600786,ALDERPOINT,224,171,76.3,53,23.7,20,8.9,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
15,1600000US0600884,600884,ALHAMBRA,84866,41442,48.8,43424,51.2,4576,5.4,...,1494,1.8,259,0.3,42796,50.4,106,0.1,2353,2.9
16,1600000US0600898,600898,ALHAMBRA VALLEY,501,237,47.3,264,52.7,31,6.2,...,0,0.0,0,0.0,9,1.8,0,0.0,114,22.8
17,1600000US0600947,600947,ALISO VIEJO,50219,23597,47.0,26622,53.0,3590,7.1,...,1035,2.1,130,0.3,7898,15.7,18,0.0,4548,9.1
18,1600000US0600982,600982,ALLEGHANY,134,28,20.9,106,79.1,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
19,1600000US0600996,600996,ALLENDALE,1349,727,53.9,622,46.1,38,2.8,...,172,12.8,7,0.5,26,1.9,0,0.0,122,9.0
20,1600000US0601010,601010,ALLENSWORTH,561,296,52.8,265,47.2,65,11.6,...,39,7.0,0,0.0,2,0.4,0,0.0,12,2.2
21,1600000US0601094,601094,ALMANOR,0,0,NaN,0,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
22,1600000US0601150,601150,ALONDRA PARK,8146,3789,46.5,4357,53.5,672,8.2,...,870,10.7,0,0.0,1809,22.2,39,0.5,374,4.5
23,1600000US0601164,601164,ALPAUGH,1124,587,52.2,537,47.8,133,11.8,...,0,0.0,41,3.6,4,0.4,0,0.0,16,1.4
24,1600000US0601192,601192,ALPINE,15188,7095,46.7,8093,53.3,954,6.3,...,193,1.3,86,0.6,219,1.4,20,0.1,601,4.0
25,1600000US0601228,601228,ALPINE VILLAGE,148,77,52.0,71,48.0,0,0.0,...,0,0.0,36,24.3,0,0.0,0,0.0,0,0.0
26,1600000US0601276,601276,ALTA,448,220,49.1,228,50.9,21,4.7,...,0,0.0,0,0.0,18,4.0,0,0.0,18,4.0
27,1600000US0601290,601290,ALTADENA,45001,22090,49.1,22911,50.9,2170,4.8,...,9556,21.2,13,0.0,3395,7.5,0,0.0,4420,9.8
28,1600000US0601360,601360,ALTA SIERRA,6639,3152,47.5,3487,52.5,230,3.5,...,0,0.0,0,0.0,72,1.1,0,0.0,234,3.6
29,1600000US0601416,601416,ALTO,649,315,48.5,334,51.5,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,49,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492,1600000US0685866,685866,WILSONIA,0,0,NaN,0,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
1493,1600000US0685880,685880,WILTON,4995,2320,46.4,2675,53.6,143,2.9,...,125,2.5,15,0.3,288,5.8,5,0.1,489,9.8
1494,1600000US0685894,685894,WINCHESTER,2407,1391,57.8,1016,42.2,119,4.9,...,41,1.7,0,0.0,0,0.0,0,0.0,94,4.0
1495,1600000US0685922,685922,WINDSOR,27318,13928,51.0,13390,49.0,1476,5.4,...,64,0.2,196,0.7,899,3.3,0,0.0,1059,4.0
1496,1600000US0685992,685992,WINTER GARDENS,21255,10782,50.7,10473,49.3,1189,5.6,...,268,1.3,77,0.4,391,1.8,18,0.1,1548,7.2
1497,1600000US0686020,686020,WINTERHAVEN,212,117,55.2,95,44.8,40,18.9,...,0,0.0,68,32.1,0,0.0,0,0.0,100,47.2
1498,1600000US0686034,686034,WINTERS,6974,3512,50.4,3462,49.6,414,5.9,...,53,0.8,44,0.6,58,0.8,0,0.0,248,3.6
1499,1600000US0686076,686076,WINTON,11309,5771,51.0,5538,49.0,1146,10.1,...,287,2.5,9,0.1,569,5.0,168,1.5,82,0.8
1500,1600000US0686174,686174,WOFFORD HEIGHTS,1590,779,49.0,811,51.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,28,1.8
1501,1600000US0686216,686216,WOODACRE,1542,775,50.3,767,49.7,47,3.0,...,0,0.0,0,0.0,9,0.6,0,0.0,18,1.2
1502,1600000US0686230,686230,WOODBRIDGE,3882,2024,52.1,1858,47.9,199,5.1,...,91,2.3,57,1.5,175,4.5,0,0.0,90,2.4
1503,1600000US0686244,686244,WOODCREST,16296,8348,51.2,7948,48.8,755,4.6,...,912,5.6,12,0.1,1129,6.9,10,0.1,350,2.1
1504,1600000US0686300,686300,WOODLAKE,7567,3756,49.6,3811,50.4,854,11.3,...,38,0.5,2,0.0,0,0.0,0,0.0,48,0.6
1505,1600000US0686328,686328,WOODLAND,57552,28174,49.0,29378,51.0,3883,6.7,...,510,0.9,203,0.4,4780,8.3,136,0.2,2731,4.8
1506,1600000US0686380,686380,WOODLANDS,1075,551,51.3,524,48.7,32,3.0,...,0,0.0,14,1.3,60,5.6,0,0.0,0,0.0
1507,1600000US0686440,686440,WOODSIDE,5496,2643,48.1,2853,51.9,190,3.5,...,0,0.0,0,0.0,254,4.6,0,0.0,168,3.1
1508,1600000US0686482,686482,WOODVILLE,1748,1010,57.8,738,42.2,184,10.5,...,0,0.0,6,0.3,0,0.0,0,0.0,16,1.0
1509,1600000US0686594,686594,WRIGHTWOOD,4510,2194,48.6,2316,51.4,441,9.8,...,0,0.0,21,0.5,17,0.4,0,0.0,322,7.1
1510,1600000US0686678,686678,YANKEE HILL,317,153,48.3,164,51.7,5,1.6,...,0,0.0,9,2.8,0,0.0,0,0.0,14,4.4
1511,1600000US0686734,686734,YETTEM,353,115,32.6,238,67.4,56,15.9,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1512,1600000US0686804,686804,YOLO,448,235,52.5,213,47.5,9,2.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1513,1600000US0686832,686832,YORBA LINDA,67362,33159,49.2,34203,50.8,3392,5.0,...,692,1.0,60,0.1,11832,17.6,55,0.1,5418,8.1
1514,1600000US0686878,686878,YOSEMITE LAKES,5081,2608,51.3,2473,48.7,227,4.5,...,8,0.2,70,1.4,42,0.8,9,0.2,169,3.4
1515,1600000US0686912,686912,YOSEMITE VALLEY,1000,633,63.3,367,36.7,21,2.1,...,36,3.6,15,1.5,97,9.7,0,0.0,0,0.0
1516,1600000US0686930,686930,YOUNTVILLE,2991,1230,41.1,1761,58.9,68,2.3,...,71,2.4,0,0.0,97,3.2,0,0.0,90,3.0
1517,1600000US0686944,686944,YREKA,7598,3408,44.9,4190,55.1,703,9.3,...,31,0.4,370,4.9,59,0.8,9,0.1,614,8.2
1518,1600000US0686972,686972,YUBA CITY,66147,32829,49.6,33318,50.4,4768,7.2,...,1553,2.3,404,0.6,12216,18.5,246,0.4,5993,9.0
1519,1600000US0687042,687042,YUCAIPA,52886,25925,49.0,26961,51.0,3729,7.1,...,749,1.4,91,0.2,1159,2.2,674,1.3,1740,3.2
1520,1600000US0687056,687056,YUCCA VALLEY,21362,10379,48.6,10983,51.4,1291,6.0,...,1245,5.8,246,1.2,440,2.1,28,0.1,1541,7.3
1521,1600000US0687090,687090,ZAYANTE,941,541,57.5,400,42.5,89,9.5,...,26,2.8,0,0.0,19,2.0,0,0.0,160,17.0

### Median Household Income and Health insurance Status

Median Household Income has categories 2,500-, 250,000+ which was changed to 2500 and 250000.

In [41]:
# Import and clean acs data for income and insurance status
acs16 = pd.read_csv("Raw_Data/Census/ACS_16_economic.csv", encoding = "ISO-8859-1", header=[0], na_values=['-'])

In [42]:
acs16.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC02_VC03,HC03_VC03,HC04_VC03,HC01_VC04,HC02_VC04,HC03_VC04,...,HC03_VC178,HC04_VC178,HC01_VC179,HC02_VC179,HC03_VC179,HC04_VC179,HC01_VC180,HC02_VC180,HC03_VC180,HC04_VC180
0,1600000US0600135,600135,"Acalanes Ridge CDP, California",747,288,747,(X),497,296,66.5,...,0.0,26.1,(X),(X),0.0,3.5,(X),(X),0.0,26.9
1,1600000US0600156,600156,"Acampo CDP, California",466,398,466,(X),368,359,79.0,...,0.0,27.6,(X),(X),0.0,9.3,(X),(X),0.0,21.6
2,1600000US0600212,600212,"Acton CDP, California",6098,398,6098,(X),3917,339,64.2,...,5.2,3.6,(X),(X),1.6,1.2,(X),(X),39.7,11.7
3,1600000US0600296,600296,"Adelanto city, California",21534,628,21534,(X),9910,597,46.0,...,21.3,6.9,(X),(X),41.5,5.6,(X),(X),49.4,5.9
4,1600000US0600310,600310,"Adin CDP, California",123,63,123,(X),51,36,41.5,...,32.5,43.5,(X),(X),0.0,28.3,(X),(X),34.0,32.3

In [43]:
acs16=acs16[['GEO.id','GEO.id2','GEO.display-label','HC01_VC85','HC01_VC131','HC03_VC131',
                'HC01_VC132','HC03_VC132','HC01_VC133','HC03_VC133','HC01_VC134','HC03_VC134']]
income16=acs16

In [44]:
income16.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC85,HC01_VC131,HC03_VC131,HC01_VC132,HC03_VC132,HC01_VC133,HC03_VC133,HC01_VC134,HC03_VC134
0,1600000US0600135,600135,"Acalanes Ridge CDP, California",187604.0,988,98.8,952,95.2,149,14.9,12,1.2
1,1600000US0600156,600156,"Acampo CDP, California",155385.0,451,96.8,451,96.8,98,21.0,15,3.2
2,1600000US0600212,600212,"Acton CDP, California",91168.0,6582,92.0,5798,81.0,1660,23.2,575,8.0
3,1600000US0600296,600296,"Adelanto city, California",29647.0,26528,86.7,9306,30.4,18268,59.7,4068,13.3
4,1600000US0600310,600310,"Adin CDP, California",55625.0,150,96.8,111,71.6,62,40.0,5,3.2

In [45]:
income16.dtypes

GEO.id                object
GEO.id2                int64
GEO.display-label     object
HC01_VC85            float64
HC01_VC131             int64
HC03_VC131           float64
HC01_VC132             int64
HC03_VC132           float64
HC01_VC133             int64
HC03_VC133           float64
HC01_VC134             int64
HC03_VC134           float64
dtype: object

In [46]:
income16.rename(columns={'GEO.display-label': 'city',
                         'HC01_VC85': 'median_income',
                         'HC01_VC131': 'insurance',
                         'HC01_VC132': 'private_insure',
                         'HC01_VC133': 'public_insure',
                         'HC01_VC134': 'no_insurance',

                         'HC03_VC131': 'insurance_pct',
                         'HC03_VC132': 'private_insure_pct',
                         'HC03_VC133': 'public_insure_pct',
                         'HC03_VC134': 'no_insurance_pct'  
                        }, 
                inplace=True)

In [47]:
income16.dtypes

GEO.id                 object
GEO.id2                 int64
city                   object
median_income         float64
insurance               int64
insurance_pct         float64
private_insure          int64
private_insure_pct    float64
public_insure           int64
public_insure_pct     float64
no_insurance            int64
no_insurance_pct      float64
dtype: object

In [48]:
income16['city']=income16.city.replace(' CDP, California', '', regex=True)

In [49]:
income16['city']=income16.city.replace(' city, California', '', regex=True)

In [50]:
income16['city']=income16.city.replace(' town, California', '', regex=True)

In [51]:
income16.head()

,GEO.id,GEO.id2,city,median_income,insurance,insurance_pct,private_insure,private_insure_pct,public_insure,public_insure_pct,no_insurance,no_insurance_pct
0,1600000US0600135,600135,Acalanes Ridge,187604.0,988,98.8,952,95.2,149,14.9,12,1.2
1,1600000US0600156,600156,Acampo,155385.0,451,96.8,451,96.8,98,21.0,15,3.2
2,1600000US0600212,600212,Acton,91168.0,6582,92.0,5798,81.0,1660,23.2,575,8.0
3,1600000US0600296,600296,Adelanto,29647.0,26528,86.7,9306,30.4,18268,59.7,4068,13.3
4,1600000US0600310,600310,Adin,55625.0,150,96.8,111,71.6,62,40.0,5,3.2

## Join Demographics and income data

In [52]:
pop_data=demographic16.merge(income16, left_on='GEO.id', right_on='GEO.id', how='outer')
pop_data

,GEO.id,GEO.id2_x,city_x,tot_pop,male,male_pct,female,female_pct,under_5,under_5_pct,...,city_y,median_income,insurance,insurance_pct,private_insure,private_insure_pct,public_insure,public_insure_pct,no_insurance,no_insurance_pct
0,1600000US0600135,600135,ACALANES RIDGE,1000,409,40.9,591,59.1,33,3.3,...,Acalanes Ridge,187604.0,988,98.8,952,95.2,149,14.9,12,1.2
1,1600000US0600156,600156,ACAMPO,466,291,62.4,175,37.6,0,0.0,...,Acampo,155385.0,451,96.8,451,96.8,98,21.0,15,3.2
2,1600000US0600212,600212,ACTON,7170,3776,52.7,3394,47.3,350,4.9,...,Acton,91168.0,6582,92.0,5798,81.0,1660,23.2,575,8.0
3,1600000US0600296,600296,ADELANTO,32311,16350,50.6,15961,49.4,3148,9.7,...,Adelanto,29647.0,26528,86.7,9306,30.4,18268,59.7,4068,13.3
4,1600000US0600310,600310,ADIN,155,59,38.1,96,61.9,7,4.5,...,Adin,55625.0,150,96.8,111,71.6,62,40.0,5,3.2
5,1600000US0600394,600394,AGOURA HILLS,20689,10132,49.0,10557,51.0,910,4.4,...,Agoura Hills,114313.0,19814,96.2,17704,85.9,4068,19.7,787,3.8
6,1600000US0600450,600450,AGUA DULCE,3541,1814,51.2,1727,48.8,208,5.9,...,Agua Dulce,104861.0,3421,96.6,3063,86.5,935,26.4,120,3.4
7,1600000US0600464,600464,AGUANGA,673,306,45.5,367,54.5,0,0.0,...,Aguanga,43750.0,501,74.4,265,39.4,298,44.3,172,25.6
8,1600000US0600478,600478,AHWAHNEE,2225,1178,52.9,1047,47.1,101,4.5,...,Ahwahnee,64049.0,2062,93.2,1432,64.7,1148,51.9,151,6.8
9,1600000US0600535,600535,AIRPORT,1605,892,55.6,713,44.4,260,16.2,...,Airport,29868.0,1298,80.9,591,36.8,741,46.2,307,19.1
10,1600000US0600562,600562,ALAMEDA,77409,37708,48.7,39701,51.3,4586,5.9,...,Alameda,83048.0,70366,92.7,58794,77.5,20088,26.5,5528,7.3
11,1600000US0600618,600618,ALAMO,16078,8394,52.2,7684,47.8,711,4.4,...,Alamo,171767.0,15707,97.8,14850,92.5,3472,21.6,352,2.2
12,1600000US0600674,600674,ALBANY,19420,9400,48.4,10020,51.6,1500,7.7,...,Albany,85458.0,18470,95.4,16020,82.8,4005,20.7,888,4.6
13,1600000US0600716,600716,ALBION,227,106,46.7,121,53.3,0,0.0,...,Albion,NaN,190,83.7,147,64.8,58,25.6,37,16.3
14,1600000US0600786,600786,ALDERPOINT,224,171,76.3,53,23.7,20,8.9,...,Alderpoint,NaN,84,37.5,29,12.9,64,28.6,140,62.5
15,1600000US0600884,600884,ALHAMBRA,84866,41442,48.8,43424,51.2,4576,5.4,...,Alhambra,53138.0,73216,86.9,48907,58.0,29740,35.3,11059,13.1
16,1600000US0600898,600898,ALHAMBRA VALLEY,501,237,47.3,264,52.7,31,6.2,...,Alhambra Valley,156250.0,494,98.6,423,84.4,168,33.5,7,1.4
17,1600000US0600947,600947,ALISO VIEJO,50219,23597,47.0,26622,53.0,3590,7.1,...,Aliso Viejo,103261.0,47325,94.3,43339,86.4,6313,12.6,2853,5.7
18,1600000US0600982,600982,ALLEGHANY,134,28,20.9,106,79.1,0,0.0,...,Alleghany,NaN,134,100.0,0,0.0,134,100.0,0,0.0
19,1600000US0600996,600996,ALLENDALE,1349,727,53.9,622,46.1,38,2.8,...,Allendale,135161.0,1220,90.4,1126,83.5,344,25.5,129,9.6
20,1600000US0601010,601010,ALLENSWORTH,561,296,52.8,265,47.2,65,11.6,...,Allensworth,29091.0,434,77.4,66,11.8,380,67.7,127,22.6
21,1600000US0601094,601094,ALMANOR,0,0,NaN,0,NaN,0,NaN,...,Almanor,NaN,0,NaN,0,NaN,0,NaN,0,NaN
22,1600000US0601150,601150,ALONDRA PARK,8146,3789,46.5,4357,53.5,672,8.2,...,Alondra Park,57406.0,6530,80.3,4121,50.7,3020,37.1,1600,19.7
23,1600000US0601164,601164,ALPAUGH,1124,587,52.2,537,47.8,133,11.8,...,Alpaugh,38750.0,891,79.3,233,20.7,701,62.4,233,20.7
24,1600000US0601192,601192,ALPINE,15188,7095,46.7,8093,53.3,954,6.3,...,Alpine,79444.0,14138,93.3,11237,74.2,5043,33.3,1011,6.7
25,1600000US0601228,601228,ALPINE VILLAGE,148,77,52.0,71,48.0,0,0.0,...,Alpine Village,68500.0,128,86.5,83,56.1,50,33.8,20,13.5
26,1600000US0601276,601276,ALTA,448,220,49.1,228,50.9,21,4.7,...,Alta,58438.0,428,95.5,295,65.8,232,51.8,20,4.5
27,1600000US0601290,601290,ALTADENA,45001,22090,49.1,22911,50.9,2170,4.8,...,Altadena,88236.0,41017,91.7,31326,70.1,14444,32.3,3698,8.3
28,1600000US0601360,601360,ALTA SIERRA,6639,3152,47.5,3487,52.5,230,3.5,...,Alta Sierra,64860.0,6001,90.6,4947,74.7,2671,40.3,621,9.4
29,1600000US0601416,601416,ALTO,649,315,48.5,334,51.5,0,0.0,...,Alto,83417.0,649,100.0,573,88.3,127,19.6,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492,1600000US0685866,685866,WILSONIA,0,0,NaN,0,NaN,0,NaN,...,Wilsonia,NaN,0,NaN,0,NaN,0,NaN,0,NaN
1493,1600000US0685880,685880,WILTON,4995,2320,46.4,2675,53.6,143,2.9,...,Wilton,86856.0,4713,94.5,4260,85.4,1487,29.8,276,5.5
1494,1600000US0685894,685894,WINCHESTER,2407,1391,57.8,1016,42.2,119,4.9,...,Winchester,37740.0,2069,86.0,839,34.9,1313,54.5,338,14.0
1495,1600000US0685922,685922,WINDSOR,27318,13928,51.0,13390,49.0,1476,5.4,...,Windsor,86192.0,24837,90.9,20579,75.3,7535,27.6,2481,9.1
1496,1600000US0685992,685992,WINTER GARDENS,21255,10782,50.7,10473,49.3,1189,5.6,...,Winter Gardens,61208.0,18852,89.2,14407,68.2,6912,32.7,2280,10.8
1497,1600000US0686020,686020,WINTERHAVEN,212,117,55.2,95,44.8,40,18.9,...,Winterhaven,22835.0,204,96.2,27,12.7,195,92.0,8,3.8
1498,1600000US0686034,686034,WINTERS,6974,3512,50.4,3462,49.6,414,5.9,...,Winters,67229.0,6081,87.3,5029,72.2,1697,24.4,882,12.7
1499,1600000US0686076,686076,WINTON,11309,5771,51.0,5538,49.0,1146,10.1,...,Winton,41486.0,9554,84.5,4299,38.0,6212,54.9,1755,15.5
1500,1600000US0686174,686174,WOFFORD HEIGHTS,1590,779,49.0,811,51.0,0,0.0,...,Wofford Heights,34167.0,1590,100.0,1109,69.7,1046,65.8,0,0.0
1501,1600000US0686216,686216,WOODACRE,1542,775,50.3,767,49.7,47,3.0,...,Woodacre,90824.0,1498,97.1,1252,81.2,513,33.3,44,2.9
1502,1600000US0686230,686230,WOODBRIDGE,3882,2024,52.1,1858,47.9,199,5.1,...,Woodbridge,75466.0,3461,89.8,2716,70.4,1425,37.0,395,10.2
1503,1600000US0686244,686244,WOODCREST,16296,8348,51.2,7948,48.8,755,4.6,...,Woodcrest,88133.0,14569,90.0,11136,68.8,4989,30.8,1621,10.0
1504,1600000US0686300,686300,WOODLAKE,7567,3756,49.6,3811,50.4,854,11.3,...,Woodlake,34583.0,6482,85.7,3012,39.8,4025,53.2,1085,14.3
1505,1600000US0686328,686328,WOODLAND,57552,28174,49.0,29378,51.0,3883,6.7,...,Woodland,56956.0,49390,87.3,34835,61.6,20566,36.4,7154,12.7
1506,1600000US0686380,686380,WOODLANDS,1075,551,51.3,524,48.7,32,3.0,...,Woodlands,140188.0,1075,100.0,977,90.9,452,42.0,0,0.0
1507,1600000US0686440,686440,WOODSIDE,5496,2643,48.1,2853,51.9,190,3.5,...,Woodside,223934.0,5351,97.4,4825,87.8,1370,24.9,145,2.6
1508,1600000US0686482,686482,WOODVILLE,1748,1010,57.8,738,42.2,184,10.5,...,Woodville,31375.0,1231,70.4,286,16.4,966,55.3,517,29.6
1509,1600000US0686594,686594,WRIGHTWOOD,4510,2194,48.6,2316,51.4,441,9.8,...,Wrightwood,60272.0,4218,93.5,3211,71.2,1415,31.4,292,6.5
1510,1600000US0686678,686678,YANKEE HILL,317,153,48.3,164,51.7,5,1.6,...,Yankee Hill,43333.0,257,81.1,132,41.6,213,67.2,60,18.9
1511,1600000US0686734,686734,YETTEM,353,115,32.6,238,67.4,56,15.9,...,Yettem,NaN,291,82.4,28,7.9,263,74.5,62,17.6
1512,1600000US0686804,686804,YOLO,448,235,52.5,213,47.5,9,2.0,...,Yolo,75792.0,371,82.8,301,67.2,80,17.9,77,17.2
1513,1600000US0686832,686832,YORBA LINDA,67362,33159,49.2,34203,50.8,3392,5.0,...,Yorba Linda,119697.0,63884,95.1,55690,82.9,14456,21.5,3299,4.9
1514,1600000US0686878,686878,YOSEMITE LAKES,5081,2608,51.3,2473,48.7,227,4.5,...,Yosemite Lakes,58430.0,4417,86.9,3389,66.7,2245,44.2,664,13.1
1515,1600000US0686912,686912,YOSEMITE VALLEY,1000,633,63.3,367,36.7,21,2.1,...,Yosemite Valley,37132.0,948,95.4,849,85.4,152,15.3,46,4.6
1516,1600000US0686930,686930,YOUNTVILLE,2991,1230,41.1,1761,58.9,68,2.3,...,Yountville,72194.0,2374,94.7,2038,81.3,1128,45.0,133,5.3
1517,1600000US0686944,686944,YREKA,7598,3408,44.9,4190,55.1,703,9.3,...,Yreka,30202.0,7000,92.4,3448,45.5,4757,62.8,578,7.6
1518,1600000US0686972,686972,YUBA CITY,66147,32829,49.6,33318,50.4,4768,7.2,...,Yuba City,50788.0,56044,86.1,34661,53.3,28214,43.4,9038,13.9
1519,1600000US0687042,687042,YUCAIPA,52886,25925,49.0,26961,51.0,3729,7.1,...,Yucaipa,55700.0,47001,89.6,32561,62.1,19533,37.2,5456,10.4
1520,1600000US0687056,687056,YUCCA VALLEY,21362,10379,48.6,10983,51.4,1291,6.0,...,Yucca Valley,41569.0,18461,88.1,10584,50.5,10800,51.6,2485,11.9
1521,1600000US0687090,687090,ZAYANTE,941,541,57.5,400,42.5,89,9.5,...,Zayante,94432.0,884,93.9,791,84.1,195,20.7,57,6.1

In [53]:
list(pop_data.columns.values)

['GEO.id',
 'GEO.id2_x',
 'city_x',
 'tot_pop',
 'male',
 'male_pct',
 'female',
 'female_pct',
 'under_5',
 'under_5_pct',
 '5_9',
 '5_9_pct',
 '10_14',
 '10_14_pct',
 '15_19',
 '15_19_pct',
 '20_24',
 '20_24_pct',
 '25_34',
 '25_34_pct',
 '35_44',
 '35_44_pct',
 '45_54',
 '45_54_pct',
 '55_59',
 '55_59_pct',
 '60_64',
 '60_64_pct',
 '65_74',
 '65_74_pct',
 '75_84',
 '75_84_pct',
 '85_over',
 '85_over_pct',
 'median_age',
 'median_age_pct',
 'hispanic_latino',
 'hispanic_latino_pct',
 'white',
 'white_pct',
 'black',
 'black_pct',
 'aian',
 'aian_pct',
 'asian',
 'asian_pct',
 'nhopi',
 'nhopi_pct',
 'other',
 'other_pct',
 'GEO.id2_y',
 'city_y',
 'median_income',
 'insurance',
 'insurance_pct',
 'private_insure',
 'private_insure_pct',
 'public_insure',
 'public_insure_pct',
 'no_insurance',
 'no_insurance_pct']

In [54]:
pop_data=pop_data.drop(columns=['GEO.id2_y','city_y'])

In [55]:
pop_data.rename(columns={'GEO.id': 'geoid',
                         'GEO.id2_x': 'geoid2',
                         'city_x': 'city'})

,geoid,geoid2,city,tot_pop,male,male_pct,female,female_pct,under_5,under_5_pct,...,other_pct,median_income,insurance,insurance_pct,private_insure,private_insure_pct,public_insure,public_insure_pct,no_insurance,no_insurance_pct
0,1600000US0600135,600135,ACALANES RIDGE,1000,409,40.9,591,59.1,33,3.3,...,32.2,187604.0,988,98.8,952,95.2,149,14.9,12,1.2
1,1600000US0600156,600156,ACAMPO,466,291,62.4,175,37.6,0,0.0,...,0.0,155385.0,451,96.8,451,96.8,98,21.0,15,3.2
2,1600000US0600212,600212,ACTON,7170,3776,52.7,3394,47.3,350,4.9,...,3.6,91168.0,6582,92.0,5798,81.0,1660,23.2,575,8.0
3,1600000US0600296,600296,ADELANTO,32311,16350,50.6,15961,49.4,3148,9.7,...,6.3,29647.0,26528,86.7,9306,30.4,18268,59.7,4068,13.3
4,1600000US0600310,600310,ADIN,155,59,38.1,96,61.9,7,4.5,...,6.4,55625.0,150,96.8,111,71.6,62,40.0,5,3.2
5,1600000US0600394,600394,AGOURA HILLS,20689,10132,49.0,10557,51.0,910,4.4,...,4.8,114313.0,19814,96.2,17704,85.9,4068,19.7,787,3.8
6,1600000US0600450,600450,AGUA DULCE,3541,1814,51.2,1727,48.8,208,5.9,...,14.2,104861.0,3421,96.6,3063,86.5,935,26.4,120,3.4
7,1600000US0600464,600464,AGUANGA,673,306,45.5,367,54.5,0,0.0,...,0.0,43750.0,501,74.4,265,39.4,298,44.3,172,25.6
8,1600000US0600478,600478,AHWAHNEE,2225,1178,52.9,1047,47.1,101,4.5,...,1.2,64049.0,2062,93.2,1432,64.7,1148,51.9,151,6.8
9,1600000US0600535,600535,AIRPORT,1605,892,55.6,713,44.4,260,16.2,...,0.8,29868.0,1298,80.9,591,36.8,741,46.2,307,19.1
10,1600000US0600562,600562,ALAMEDA,77409,37708,48.7,39701,51.3,4586,5.9,...,12.5,83048.0,70366,92.7,58794,77.5,20088,26.5,5528,7.3
11,1600000US0600618,600618,ALAMO,16078,8394,52.2,7684,47.8,711,4.4,...,4.8,171767.0,15707,97.8,14850,92.5,3472,21.6,352,2.2
12,1600000US0600674,600674,ALBANY,19420,9400,48.4,10020,51.6,1500,7.7,...,13.6,85458.0,18470,95.4,16020,82.8,4005,20.7,888,4.6
13,1600000US0600716,600716,ALBION,227,106,46.7,121,53.3,0,0.0,...,22.0,NaN,190,83.7,147,64.8,58,25.6,37,16.3
14,1600000US0600786,600786,ALDERPOINT,224,171,76.3,53,23.7,20,8.9,...,0.0,NaN,84,37.5,29,12.9,64,28.6,140,62.5
15,1600000US0600884,600884,ALHAMBRA,84866,41442,48.8,43424,51.2,4576,5.4,...,2.9,53138.0,73216,86.9,48907,58.0,29740,35.3,11059,13.1
16,1600000US0600898,600898,ALHAMBRA VALLEY,501,237,47.3,264,52.7,31,6.2,...,22.8,156250.0,494,98.6,423,84.4,168,33.5,7,1.4
17,1600000US0600947,600947,ALISO VIEJO,50219,23597,47.0,26622,53.0,3590,7.1,...,9.1,103261.0,47325,94.3,43339,86.4,6313,12.6,2853,5.7
18,1600000US0600982,600982,ALLEGHANY,134,28,20.9,106,79.1,0,0.0,...,0.0,NaN,134,100.0,0,0.0,134,100.0,0,0.0
19,1600000US0600996,600996,ALLENDALE,1349,727,53.9,622,46.1,38,2.8,...,9.0,135161.0,1220,90.4,1126,83.5,344,25.5,129,9.6
20,1600000US0601010,601010,ALLENSWORTH,561,296,52.8,265,47.2,65,11.6,...,2.2,29091.0,434,77.4,66,11.8,380,67.7,127,22.6
21,1600000US0601094,601094,ALMANOR,0,0,NaN,0,NaN,0,NaN,...,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN
22,1600000US0601150,601150,ALONDRA PARK,8146,3789,46.5,4357,53.5,672,8.2,...,4.5,57406.0,6530,80.3,4121,50.7,3020,37.1,1600,19.7
23,1600000US0601164,601164,ALPAUGH,1124,587,52.2,537,47.8,133,11.8,...,1.4,38750.0,891,79.3,233,20.7,701,62.4,233,20.7
24,1600000US0601192,601192,ALPINE,15188,7095,46.7,8093,53.3,954,6.3,...,4.0,79444.0,14138,93.3,11237,74.2,5043,33.3,1011,6.7
25,1600000US0601228,601228,ALPINE VILLAGE,148,77,52.0,71,48.0,0,0.0,...,0.0,68500.0,128,86.5,83,56.1,50,33.8,20,13.5
26,1600000US0601276,601276,ALTA,448,220,49.1,228,50.9,21,4.7,...,4.0,58438.0,428,95.5,295,65.8,232,51.8,20,4.5
27,1600000US0601290,601290,ALTADENA,45001,22090,49.1,22911,50.9,2170,4.8,...,9.8,88236.0,41017,91.7,31326,70.1,14444,32.3,3698,8.3
28,1600000US0601360,601360,ALTA SIERRA,6639,3152,47.5,3487,52.5,230,3.5,...,3.6,64860.0,6001,90.6,4947,74.7,2671,40.3,621,9.4
29,1600000US0601416,601416,ALTO,649,315,48.5,334,51.5,0,0.0,...,7.5,83417.0,649,100.0,573,88.3,127,19.6,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492,1600000US0685866,685866,WILSONIA,0,0,NaN,0,NaN,0,NaN,...,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN
1493,1600000US0685880,685880,WILTON,4995,2320,46.4,2675,53.6,143,2.9,...,9.8,86856.0,4713,94.5,4260,85.4,1487,29.8,276,5.5
1494,1600000US0685894,685894,WINCHESTER,2407,1391,57.8,1016,42.2,119,4.9,...,4.0,37740.0,2069,86.0,839,34.9,1313,54.5,338,14.0
1495,1600000US0685922,685922,WINDSOR,27318,13928,51.0,13390,49.0,1476,5.4,...,4.0,86192.0,24837,90.9,20579,75.3,7535,27.6,2481,9.1
1496,1600000US0685992,685992,WINTER GARDENS,21255,10782,50.7,10473,49.3,1189,5.6,...,7.2,61208.0,18852,89.2,14407,68.2,6912,32.7,2280,10.8
1497,1600000US0686020,686020,WINTERHAVEN,212,117,55.2,95,44.8,40,18.9,...,47.2,22835.0,204,96.2,27,12.7,195,92.0,8,3.8
1498,1600000US0686034,686034,WINTERS,6974,3512,50.4,3462,49.6,414,5.9,...,3.6,67229.0,6081,87.3,5029,72.2,1697,24.4,882,12.7
1499,1600000US0686076,686076,WINTON,11309,5771,51.0,5538,49.0,1146,10.1,...,0.8,41486.0,9554,84.5,4299,38.0,6212,54.9,1755,15.5
1500,1600000US0686174,686174,WOFFORD HEIGHTS,1590,779,49.0,811,51.0,0,0.0,...,1.8,34167.0,1590,100.0,1109,69.7,1046,65.8,0,0.0
1501,1600000US0686216,686216,WOODACRE,1542,775,50.3,767,49.7,47,3.0,...,1.2,90824.0,1498,97.1,1252,81.2,513,33.3,44,2.9
1502,1600000US0686230,686230,WOODBRIDGE,3882,2024,52.1,1858,47.9,199,5.1,...,2.4,75466.0,3461,89.8,2716,70.4,1425,37.0,395,10.2
1503,1600000US0686244,686244,WOODCREST,16296,8348,51.2,7948,48.8,755,4.6,...,2.1,88133.0,14569,90.0,11136,68.8,4989,30.8,1621,10.0
1504,1600000US0686300,686300,WOODLAKE,7567,3756,49.6,3811,50.4,854,11.3,...,0.6,34583.0,6482,85.7,3012,39.8,4025,53.2,1085,14.3
1505,1600000US0686328,686328,WOODLAND,57552,28174,49.0,29378,51.0,3883,6.7,...,4.8,56956.0,49390,87.3,34835,61.6,20566,36.4,7154,12.7
1506,1600000US0686380,686380,WOODLANDS,1075,551,51.3,524,48.7,32,3.0,...,0.0,140188.0,1075,100.0,977,90.9,452,42.0,0,0.0
1507,1600000US0686440,686440,WOODSIDE,5496,2643,48.1,2853,51.9,190,3.5,...,3.1,223934.0,5351,97.4,4825,87.8,1370,24.9,145,2.6
1508,1600000US0686482,686482,WOODVILLE,1748,1010,57.8,738,42.2,184,10.5,...,1.0,31375.0,1231,70.4,286,16.4,966,55.3,517,29.6
1509,1600000US0686594,686594,WRIGHTWOOD,4510,2194,48.6,2316,51.4,441,9.8,...,7.1,60272.0,4218,93.5,3211,71.2,1415,31.4,292,6.5
1510,1600000US0686678,686678,YANKEE HILL,317,153,48.3,164,51.7,5,1.6,...,4.4,43333.0,257,81.1,132,41.6,213,67.2,60,18.9
1511,1600000US0686734,686734,YETTEM,353,115,32.6,238,67.4,56,15.9,...,0.0,NaN,291,82.4,28,7.9,263,74.5,62,17.6
1512,1600000US0686804,686804,YOLO,448,235,52.5,213,47.5,9,2.0,...,0.0,75792.0,371,82.8,301,67.2,80,17.9,77,17.2
1513,1600000US0686832,686832,YORBA LINDA,67362,33159,49.2,34203,50.8,3392,5.0,...,8.1,119697.0,63884,95.1,55690,82.9,14456,21.5,3299,4.9
1514,1600000US0686878,686878,YOSEMITE LAKES,5081,2608,51.3,2473,48.7,227,4.5,...,3.4,58430.0,4417,86.9,3389,66.7,2245,44.2,664,13.1
1515,1600000US0686912,686912,YOSEMITE VALLEY,1000,633,63.3,367,36.7,21,2.1,...,0.0,37132.0,948,95.4,849,85.4,152,15.3,46,4.6
1516,1600000US0686930,686930,YOUNTVILLE,2991,1230,41.1,1761,58.9,68,2.3,...,3.0,72194.0,2374,94.7,2038,81.3,1128,45.0,133,5.3
1517,1600000US0686944,686944,YREKA,7598,3408,44.9,4190,55.1,703,9.3,...,8.2,30202.0,7000,92.4,3448,45.5,4757,62.8,578,7.6
1518,1600000US0686972,686972,YUBA CITY,66147,32829,49.6,33318,50.4,4768,7.2,...,9.0,50788.0,56044,86.1,34661,53.3,28214,43.4,9038,13.9
1519,1600000US0687042,687042,YUCAIPA,52886,25925,49.0,26961,51.0,3729,7.1,...,3.2,55700.0,47001,89.6,32561,62.1,19533,37.2,5456,10.4
1520,1600000US0687056,687056,YUCCA VALLEY,21362,10379,48.6,10983,51.4,1291,6.0,...,7.3,41569.0,18461,88.1,10584,50.5,10800,51.6,2485,11.9
1521,1600000US0687090,687090,ZAYANTE,941,541,57.5,400,42.5,89,9.5,...,17.0,94432.0,884,93.9,791,84.1,195,20.7,57,6.1

In [56]:
# Exported merged census data
pop_data.to_csv("pop_data16.csv", index=False)

## Join Vaccine data to Census data

Join needs unique cities in the vaccine data to use as a key. Will need to figure out how to weight the different grade levels based on the census population numbers for age.

In [57]:
vac_pop_1718=vac_1718.merge(pop_data, left_on='CITY', right_on='city', how='outer')
vac_pop_1718

KeyError: 'city'