In [1]:
import numpy as np
import pandas as pd

## Census Data Cleaning

### Demographics

In [2]:
# Import and clean census data for basic demographics age gender race is DP05 file
census = pd.read_csv("vaxxfacts/raw_data/Census/ACS_11_5YR_DP05.csv",encoding = "ISO-8859-1",
                       header=[0],na_values=['-'],)

In [3]:
census.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC02_VC03,HC03_VC03,HC04_VC03,HC01_VC04,HC02_VC04,HC03_VC04,...,HC03_VC95,HC04_VC95,HC01_VC96,HC02_VC96,HC03_VC96,HC04_VC96,HC01_VC98,HC02_VC98,HC03_VC98,HC04_VC98
0,1600000US0600135,600135,"Acalanes Ridge CDP, California",1431,428.0,1431,NaN,705,199,49.3,...,0.0,2.6,173,251,12.1,15.6,482,99,NaN,NaN
1,1600000US0600156,600156,"Acampo CDP, California",387,564.0,387,NaN,263,384,68.0,...,0.0,9.2,0,95,0.0,9.2,71,97,NaN,NaN
2,1600000US0600212,600212,"Acton CDP, California",7138,620.0,7138,NaN,3596,380,50.4,...,0.0,0.5,139,82,1.9,1.1,2618,187,NaN,NaN
3,1600000US0600296,600296,"Adelanto city, California",30670,40.0,30670,NaN,16740,741,54.6,...,0.1,0.2,1516,679,4.9,2.2,8417,484,NaN,NaN
4,1600000US0600310,600310,"Adin CDP, California",418,206.0,418,NaN,211,118,50.5,...,0.0,8.6,0,95,0.0,8.6,214,67,NaN,NaN

In [4]:
census.dtypes

GEO.id                object
GEO.id2                int64
GEO.display-label     object
HC01_VC03              int64
HC02_VC03            float64
HC03_VC03              int64
HC04_VC03            float64
HC01_VC04              int64
HC02_VC04              int64
HC03_VC04            float64
HC04_VC04            float64
HC01_VC05              int64
HC02_VC05              int64
HC03_VC05            float64
HC04_VC05            float64
HC01_VC07              int64
HC02_VC07            float64
HC03_VC07            float64
HC04_VC07            float64
HC01_VC08              int64
HC02_VC08              int64
HC03_VC08            float64
HC04_VC08            float64
HC01_VC09              int64
HC02_VC09              int64
HC03_VC09            float64
HC04_VC09            float64
HC01_VC10              int64
HC02_VC10              int64
HC03_VC10            float64
                      ...
HC03_VC90            float64
HC04_VC90            float64
HC01_VC91              int64
HC02_VC91              int64
HC03_VC91            float64
HC04_VC91            float64
HC01_VC92              int64
HC02_VC92              int64
HC03_VC92            float64
HC04_VC92            float64
HC01_VC93              int64
HC02_VC93              int64
HC03_VC93            float64
HC04_VC93            float64
HC01_VC94              int64
HC02_VC94              int64
HC03_VC94            float64
HC04_VC94            float64
HC01_VC95              int64
HC02_VC95              int64
HC03_VC95            float64
HC04_VC95            float64
HC01_VC96              int64
HC02_VC96              int64
HC03_VC96            float64
HC04_VC96            float64
HC01_VC98              int64
HC02_VC98              int64
HC03_VC98            float64
HC04_VC98            float64
Length: 327, dtype: object

In [5]:
demographic = census[['GEO.id','GEO.id2','GEO.display-label',
                         'HC01_VC03',
                         'HC01_VC04', 'HC03_VC04',
                         'HC01_VC05', 'HC03_VC05',
                         'HC01_VC07', 'HC03_VC07',
                         'HC01_VC08', 'HC03_VC08',
                         'HC01_VC09', 'HC03_VC09',
                         'HC01_VC10', 'HC03_VC10',
                         'HC01_VC11', 'HC03_VC11',
                         'HC01_VC12', 'HC03_VC12',
                         'HC01_VC13', 'HC03_VC13',
                         'HC01_VC14', 'HC03_VC14',
                         'HC01_VC15', 'HC03_VC15',
                         'HC01_VC16', 'HC03_VC16',
                         'HC01_VC17', 'HC03_VC17',
                         'HC01_VC18', 'HC03_VC18',
                         'HC01_VC19', 'HC03_VC19',
                         'HC01_VC21', 'HC03_VC21',
                         'HC01_VC82', 'HC03_VC82',
                         'HC01_VC83', 'HC03_VC83',
                         'HC01_VC88', 'HC03_VC88',
                         'HC01_VC89', 'HC03_VC89',
                         'HC01_VC90', 'HC03_VC90',
                         'HC01_VC91', 'HC03_VC91',
                         'HC01_VC92', 'HC03_VC92',

                         'HC01_VC93', 'HC03_VC93',
                         'HC01_VC94', 'HC03_VC94',
                         'HC01_VC95', 'HC03_VC95',
                         'HC01_VC96', 'HC03_VC96']]

In [6]:
demographic.dtypes

GEO.id                object
GEO.id2                int64
GEO.display-label     object
HC01_VC03              int64
HC01_VC04              int64
HC03_VC04            float64
HC01_VC05              int64
HC03_VC05            float64
HC01_VC07              int64
HC03_VC07            float64
HC01_VC08              int64
HC03_VC08            float64
HC01_VC09              int64
HC03_VC09            float64
HC01_VC10              int64
HC03_VC10            float64
HC01_VC11              int64
HC03_VC11            float64
HC01_VC12              int64
HC03_VC12            float64
HC01_VC13              int64
HC03_VC13            float64
HC01_VC14              int64
HC03_VC14            float64
HC01_VC15              int64
HC03_VC15            float64
HC01_VC16              int64
HC03_VC16            float64
HC01_VC17              int64
HC03_VC17            float64
HC01_VC18              int64
HC03_VC18            float64
HC01_VC19              int64
HC03_VC19            float64
HC01_VC21            float64
HC03_VC21            float64
HC01_VC82              int64
HC03_VC82            float64
HC01_VC83              int64
HC03_VC83            float64
HC01_VC88              int64
HC03_VC88            float64
HC01_VC89              int64
HC03_VC89            float64
HC01_VC90              int64
HC03_VC90            float64
HC01_VC91              int64
HC03_VC91            float64
HC01_VC92              int64
HC03_VC92            float64
HC01_VC93              int64
HC03_VC93            float64
HC01_VC94              int64
HC03_VC94            float64
HC01_VC95              int64
HC03_VC95            float64
HC01_VC96              int64
HC03_VC96            float64
dtype: object

In [7]:
#combine other race, two or more races (HC01_VC99, HC01_VC100, HC01_VC101, HC01_VC102)
demographic['other']=pd.Series(census['HC01_VC93']+census['HC01_VC94']+census['HC01_VC95']+census['HC01_VC96'])

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
demographic['other_pct']=pd.Series(census['HC03_VC93']+census['HC03_VC94']+census['HC03_VC95']+census['HC03_VC96'])

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [9]:
demographic.rename(columns={'GEO.display-label': 'city',
                         'HC01_VC03': 'tot_pop', 
                         'HC01_VC04': 'male',
                         'HC01_VC05': 'female',
                         'HC01_VC07':'under_5',
                         'HC01_VC08':'5_9',
                         'HC01_VC09':'10_14',
                         'HC01_VC10':'15_19',
                         'HC01_VC11':'20_24',
                         'HC01_VC12':'25_34',
                         'HC01_VC13':'35_44',
                         'HC01_VC14':'45_54',
                         'HC01_VC15':'55_59',
                         'HC01_VC16':'60_64',
                         'HC01_VC17':'65_74',
                         'HC01_VC18':'75_84',
                         'HC01_VC19':'85_over',
                         'HC01_VC21':'median_age',
                         'HC01_VC82':'hispanic_latino',
                         'HC01_VC83':'mexican',
                         'HC01_VC88':'white',
                         'HC01_VC89':'black',
                         'HC01_VC90':'aian',
                         'HC01_VC91':'asian',
                         'HC01_VC92':'nhopi',

                         'HC03_VC04': 'male_pct',
                         'HC03_VC05': 'female_pct',
                         'HC03_VC07':'under_5_pct',
                         'HC03_VC08':'5_9_pct',
                         'HC03_VC09':'10_14_pct',
                         'HC03_VC10':'15_19_pct',
                         'HC03_VC11':'20_24_pct',
                         'HC03_VC12':'25_34_pct',
                         'HC03_VC13':'35_44_pct',
                         'HC03_VC14':'45_54_pct',
                         'HC03_VC15':'55_59_pct',
                         'HC03_VC16':'60_64_pct',
                         'HC03_VC17':'65_74_pct',
                         'HC03_VC18':'75_84_pct',
                         'HC03_VC19':'85_over_pct',
                         'HC03_VC21':'median_age_pct',
                         'HC03_VC82':'hispanic_latino_pct',
                         'HC03_VC83':'mexican_pct',
                         'HC03_VC88':'white_pct',
                         'HC03_VC89':'black_pct',
                         'HC03_VC90':'aian_pct',
                         'HC03_VC91':'asian_pct',
                         'HC03_VC92':'nhopi_pct'
                        }, 
                inplace=True)

# AIAN is american Indian Alaskan Native
# NHOPI is Native Hawaiian and Other Pacific Islander

# Other race categories
#                          'HC01_VC93':'other_only',
#                          'HC01_VC94':'more_two_races',
#                          'HC01_VC95':'more_two_races_other',
#                          'HC01_VC96':'more_two_races_other_exclude',

C:\Users\42\Anaconda3\lib\site-packages\pandas\core\frame.py:3778: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [10]:
demographic.dtypes

GEO.id                  object
GEO.id2                  int64
city                    object
tot_pop                  int64
male                     int64
male_pct               float64
female                   int64
female_pct             float64
under_5                  int64
under_5_pct            float64
5_9                      int64
5_9_pct                float64
10_14                    int64
10_14_pct              float64
15_19                    int64
15_19_pct              float64
20_24                    int64
20_24_pct              float64
25_34                    int64
25_34_pct              float64
35_44                    int64
35_44_pct              float64
45_54                    int64
45_54_pct              float64
55_59                    int64
55_59_pct              float64
60_64                    int64
60_64_pct              float64
65_74                    int64
65_74_pct              float64
75_84                    int64
75_84_pct              float64
85_over                  int64
85_over_pct            float64
median_age             float64
median_age_pct         float64
hispanic_latino          int64
hispanic_latino_pct    float64
mexican                  int64
mexican_pct            float64
white                    int64
white_pct              float64
black                    int64
black_pct              float64
aian                     int64
aian_pct               float64
asian                    int64
asian_pct              float64
nhopi                    int64
nhopi_pct              float64
HC01_VC93                int64
HC03_VC93              float64
HC01_VC94                int64
HC03_VC94              float64
HC01_VC95                int64
HC03_VC95              float64
HC01_VC96                int64
HC03_VC96              float64
other                    int64
other_pct              float64
dtype: object

In [11]:
demographic['city']=demographic.city.replace(' city, California', '', regex=True)

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [12]:
demographic['city']=demographic.city.replace(' CDP, California', '', regex=True)

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
demographic['city']=demographic.city.replace(' town, California', '', regex=True)

C:\Users\42\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
demographic=demographic.drop(columns=['HC01_VC93','HC03_VC93','HC01_VC94','HC03_VC94','HC01_VC95','HC03_VC95','HC01_VC96','HC03_VC96'])
demographic

,GEO.id,GEO.id2,city,tot_pop,male,male_pct,female,female_pct,under_5,under_5_pct,...,black,black_pct,aian,aian_pct,asian,asian_pct,nhopi,nhopi_pct,other,other_pct
0,1600000US0600135,600135,Acalanes Ridge,1431,705,49.3,726,50.7,126,8.8,...,0,0.0,0,0.0,146,10.2,37,2.6,346,24.2
1,1600000US0600156,600156,Acampo,387,263,68.0,124,32.0,55,14.2,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,1600000US0600212,600212,Acton,7138,3596,50.4,3542,49.6,488,6.8,...,11,0.2,0,0.0,88,1.2,0,0.0,281,3.8
3,1600000US0600296,600296,Adelanto,30670,16740,54.6,13930,45.4,3364,11.0,...,6397,20.9,69,0.2,683,2.2,262,0.9,3181,10.3
4,1600000US0600310,600310,Adin,418,211,50.5,207,49.5,21,5.0,...,0,0.0,14,3.3,0,0.0,0,0.0,0,0.0
5,1600000US0600394,600394,Agoura Hills,20353,10515,51.7,9838,48.3,749,3.7,...,319,1.6,0,0.0,1249,6.1,0,0.0,986,4.8
6,1600000US0600450,600450,Agua Dulce,2991,1388,46.4,1603,53.6,86,2.9,...,0,0.0,0,0.0,24,0.8,0,0.0,132,4.4
7,1600000US0600464,600464,Aguanga,1540,750,48.7,790,51.3,14,0.9,...,42,2.7,0,0.0,0,0.0,0,0.0,46,3.0
8,1600000US0600478,600478,Ahwahnee,1685,795,47.2,890,52.8,0,0.0,...,0,0.0,0,0.0,1,0.1,0,0.0,0,0.0
9,1600000US0600535,600535,Airport,1490,827,55.5,663,44.5,115,7.7,...,0,0.0,75,5.0,0,0.0,0,0.0,0,0.0
10,1600000US0600562,600562,Alameda,73239,35212,48.1,38027,51.9,4119,5.6,...,4721,6.4,135,0.2,23847,32.6,382,0.5,7487,10.3
11,1600000US0600618,600618,Alamo,15531,7683,49.5,7848,50.5,646,4.2,...,91,0.6,12,0.1,1082,7.0,26,0.2,828,5.4
12,1600000US0600674,600674,Albany,18217,8731,47.9,9486,52.1,1437,7.9,...,550,3.0,10,0.1,5278,29.0,17,0.1,1937,10.5
13,1600000US0600716,600716,Albion,255,162,63.5,93,36.5,0,0.0,...,0,0.0,0,0.0,14,5.5,0,0.0,30,11.8
14,1600000US0600786,600786,Alderpoint,113,59,52.2,54,47.8,6,5.3,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
15,1600000US0600884,600884,Alhambra,83301,39799,47.8,43502,52.2,4101,4.9,...,1217,1.5,142,0.2,44324,53.2,99,0.1,1960,2.3
16,1600000US0600898,600898,Alhambra Valley,910,521,57.3,389,42.7,40,4.4,...,0,0.0,0,0.0,13,1.4,0,0.0,0,0.0
17,1600000US0600947,600947,Aliso Viejo,47037,22226,47.3,24811,52.7,3983,8.5,...,1536,3.3,8,0.0,6294,13.4,19,0.0,3251,6.9
18,1600000US0600982,600982,Alleghany,65,49,75.4,16,24.6,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
19,1600000US0600996,600996,Allendale,1968,1024,52.0,944,48.0,39,2.0,...,0,0.0,0,0.0,63,3.2,0,0.0,156,7.9
20,1600000US0601010,601010,Allensworth,281,133,47.3,148,52.7,15,5.3,...,20,7.1,0,0.0,5,1.8,0,0.0,2,0.8
21,1600000US0601094,601094,Almanor,10,10,100.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
22,1600000US0601150,601150,Alondra Park,8358,4120,49.3,4238,50.7,769,9.2,...,927,11.1,0,0.0,1219,14.6,72,0.9,202,2.5
23,1600000US0601164,601164,Alpaugh,847,406,47.9,441,52.1,159,18.8,...,20,2.4,13,1.5,0,0.0,0,0.0,12,1.4
24,1600000US0601192,601192,Alpine,13332,6536,49.0,6796,51.0,593,4.4,...,166,1.2,95,0.7,167,1.3,0,0.0,714,5.3
25,1600000US0601228,601228,Alpine Village,180,110,61.1,70,38.9,36,20.0,...,0,0.0,95,52.8,0,0.0,0,0.0,0,0.0
26,1600000US0601276,601276,Alta,549,273,49.7,276,50.3,6,1.1,...,0,0.0,0,0.0,0,0.0,2,0.4,20,3.6
27,1600000US0601290,601290,Altadena,45006,21920,48.7,23086,51.3,2872,6.4,...,10261,22.8,24,0.1,1808,4.0,119,0.3,2763,6.2
28,1600000US0601360,601360,Alta Sierra,6888,3151,45.7,3737,54.3,201,2.9,...,0,0.0,12,0.2,106,1.5,68,1.0,346,5.1
29,1600000US0601416,601416,Alto,741,335,45.2,406,54.8,35,4.7,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1493,1600000US0685866,685866,Wilsonia,0,0,NaN,0,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
1494,1600000US0685880,685880,Wilton,4364,2217,50.8,2147,49.2,190,4.4,...,42,1.0,33,0.8,356,8.2,0,0.0,457,10.5
1495,1600000US0685894,685894,Winchester,2955,1470,49.7,1485,50.3,121,4.1,...,0,0.0,0,0.0,162,5.5,0,0.0,282,9.6
1496,1600000US0685922,685922,Windsor,26229,12439,47.4,13790,52.6,1496,5.7,...,122,0.5,321,1.2,728,2.8,173,0.7,734,2.8
1497,1600000US0685992,685992,Winter Gardens,20143,9582,47.6,10561,52.4,1502,7.5,...,306,1.5,23,0.1,127,0.6,19,0.1,2112,10.5
1498,1600000US0686020,686020,Winterhaven,493,183,37.1,310,62.9,146,29.6,...,0,0.0,17,3.4,53,10.8,0,0.0,0,0.0
1499,1600000US0686034,686034,Winters,6616,3259,49.3,3357,50.7,585,8.8,...,0,0.0,18,0.3,250,3.8,20,0.3,470,7.1
1500,1600000US0686076,686076,Winton,11742,6145,52.3,5597,47.7,993,8.5,...,183,1.6,0,0.0,958,8.2,0,0.0,54,0.4
1501,1600000US0686174,686174,Wofford Heights,2284,1175,51.4,1109,48.6,227,9.9,...,0,0.0,13,0.6,0,0.0,0,0.0,26,1.2
1502,1600000US0686216,686216,Woodacre,1470,751,51.1,719,48.9,52,3.5,...,45,3.1,0,0.0,62,4.2,0,0.0,0,0.0
1503,1600000US0686230,686230,Woodbridge,4153,2071,49.9,2082,50.1,182,4.4,...,0,0.0,0,0.0,251,6.0,0,0.0,298,7.2
1504,1600000US0686244,686244,Woodcrest,14519,7173,49.4,7346,50.6,942,6.5,...,446,3.1,34,0.2,573,3.9,31,0.2,858,6.0
1505,1600000US0686300,686300,Woodlake,7252,3816,52.6,3436,47.4,754,10.4,...,0,0.0,13,0.2,27,0.4,0,0.0,358,5.0
1506,1600000US0686328,686328,Woodland,55229,27390,49.6,27839,50.4,4252,7.7,...,656,1.2,350,0.6,3543,6.4,117,0.2,1825,3.3
1507,1600000US0686380,686380,Woodlands,417,224,53.7,193,46.3,0,0.0,...,0,0.0,14,3.4,16,3.8,0,0.0,30,7.2
1508,1600000US0686440,686440,Woodside,5263,2629,50.0,2634,50.0,194,3.7,...,11,0.2,21,0.4,229,4.4,0,0.0,350,6.7
1509,1600000US0686482,686482,Woodville,1992,1020,51.2,972,48.8,223,11.2,...,0,0.0,5,0.3,0,0.0,0,0.0,0,0.0
1510,1600000US0686594,686594,Wrightwood,4556,2252,49.4,2304,50.6,388,8.5,...,0,0.0,0,0.0,43,0.9,0,0.0,0,0.0
1511,1600000US0686678,686678,Yankee Hill,240,126,52.5,114,47.5,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,42,17.6
1512,1600000US0686734,686734,Yettem,279,124,44.4,155,55.6,31,11.1,...,0,0.0,0,0.0,0,0.0,0,0.0,2,0.8
1513,1600000US0686804,686804,Yolo,335,227,67.8,108,32.2,18,5.4,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1514,1600000US0686832,686832,Yorba Linda,63578,31580,49.7,31998,50.3,3500,5.5,...,888,1.4,356,0.6,9752,15.3,10,0.0,3691,5.9
1515,1600000US0686878,686878,Yosemite Lakes,4655,2492,53.5,2163,46.5,298,6.4,...,10,0.2,74,1.6,76,1.6,0,0.0,46,1.0
1516,1600000US0686912,686912,Yosemite Valley,779,577,74.1,202,25.9,0,0.0,...,47,6.0,0,0.0,8,1.0,0,0.0,0,0.0
1517,1600000US0686930,686930,Yountville,2943,1443,49.0,1500,51.0,58,2.0,...,57,1.9,14,0.5,48,1.6,0,0.0,108,3.6
1518,1600000US0686944,686944,Yreka,7696,3667,47.6,4029,52.4,528,6.9,...,98,1.3,167,2.2,145,1.9,48,0.6,1040,13.6
1519,1600000US0686972,686972,Yuba City,64224,31826,49.6,32398,50.4,5119,8.0,...,1434,2.2,529,0.8,11090,17.3,203,0.3,4822,7.5
1520,1600000US0687042,687042,Yucaipa,50862,25823,50.8,25039,49.2,2797,5.5,...,928,1.8,307,0.6,1199,2.4,21,0.0,2654,5.3
1521,1600000US0687056,687056,Yucca Valley,20508,9906,48.3,10602,51.7,1310,6.4,...,471,2.3,150,0.7,500,2.4,28,0.1,1112,5.4
1522,1600000US0687090,687090,Zayante,781,344,44.0,437,56.0,37,4.7,...,0,0.0,0,0.0,0,0.0,0,0.0,20,2.6

### Median Household Income and Health insurance Status

Median Household Income has categories 2,500-, 250,000+ which was changed to 2500 and 250000.

In [15]:
# Import and clean acs data for income and insurance status
acs = pd.read_csv("vaxxfacts/raw_data/Census/ACS_11_5YR_DP03.csv", encoding = "ISO-8859-1", header=[0], na_values=['-'])

In [16]:
acs.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC04,HC02_VC04,HC03_VC04,HC04_VC04,HC01_VC05,HC02_VC05,HC03_VC05,...,HC03_VC173,HC04_VC173,HC01_VC174,HC02_VC174,HC03_VC174,HC04_VC174,HC01_VC175,HC02_VC175,HC03_VC175,HC04_VC175
0,1600000US0600135,600135,"Acalanes Ridge CDP, California",1018,239,1018,NaN,792,233,77.8,...,0.0,30.5,NaN,NaN,0.0,2.9,NaN,NaN,14.0,18.4
1,1600000US0600156,600156,"Acampo CDP, California",332,478,332,NaN,276,390,83.1,...,NaN,NaN,NaN,NaN,0.0,9.2,NaN,NaN,NaN,NaN
2,1600000US0600212,600212,"Acton CDP, California",5714,531,5714,NaN,3500,411,61.3,...,0.0,4.5,NaN,NaN,8.5,6.1,NaN,NaN,6.6,5.6
3,1600000US0600296,600296,"Adelanto city, California",19761,697,19761,NaN,10139,707,51.3,...,13.3,8.1,NaN,NaN,26.9,5.9,NaN,NaN,37.5,9.9
4,1600000US0600310,600310,"Adin CDP, California",315,105,315,NaN,164,88,52.1,...,10.5,18.8,NaN,NaN,7.2,12.7,NaN,NaN,7.2,15.3

In [17]:
acs=acs[['GEO.id','GEO.id2','GEO.display-label','HC01_VC85','HC01_VC128','HC03_VC128',
                'HC01_VC129','HC03_VC129','HC01_VC130','HC03_VC130','HC01_VC131','HC03_VC131']]
income=acs

In [18]:
income.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC85,HC01_VC128,HC03_VC128,HC01_VC129,HC03_VC129,HC01_VC130,HC03_VC130,HC01_VC131,HC03_VC131
0,1600000US0600135,600135,"Acalanes Ridge CDP, California",138672.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1600000US0600156,600156,"Acampo CDP, California",121455.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1600000US0600212,600212,"Acton CDP, California",87896.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1600000US0600296,600296,"Adelanto city, California",42208.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1600000US0600310,600310,"Adin CDP, California",45625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
income.dtypes

GEO.id                object
GEO.id2                int64
GEO.display-label     object
HC01_VC85            float64
HC01_VC128           float64
HC03_VC128           float64
HC01_VC129           float64
HC03_VC129           float64
HC01_VC130           float64
HC03_VC130           float64
HC01_VC131           float64
HC03_VC131           float64
dtype: object

In [20]:
income.rename(columns={'GEO.display-label': 'city',
                         'HC01_VC85': 'median_income',
                         'HC01_VC128': 'insurance',
                         'HC01_VC129': 'private_insure',
                         'HC01_VC130': 'public_insure',
                         'HC01_VC131': 'no_insurance',

                         'HC03_VC128': 'insurance_pct',
                         'HC03_VC129': 'private_insure_pct',
                         'HC03_VC130': 'public_insure_pct',
                         'HC03_VC131': 'no_insurance_pct'  
                        }, 
                inplace=True)

In [21]:
income.dtypes

GEO.id                 object
GEO.id2                 int64
city                   object
median_income         float64
insurance             float64
insurance_pct         float64
private_insure        float64
private_insure_pct    float64
public_insure         float64
public_insure_pct     float64
no_insurance          float64
no_insurance_pct      float64
dtype: object

In [22]:
income['city']=income.city.replace(' CDP, California', '', regex=True)

In [23]:
income['city']=income.city.replace(' city, California', '', regex=True)

In [24]:
income['city']=income.city.replace(' town, California', '', regex=True)

In [25]:
income.head()

,GEO.id,GEO.id2,city,median_income,insurance,insurance_pct,private_insure,private_insure_pct,public_insure,public_insure_pct,no_insurance,no_insurance_pct
0,1600000US0600135,600135,Acalanes Ridge,138672.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1600000US0600156,600156,Acampo,121455.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1600000US0600212,600212,Acton,87896.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1600000US0600296,600296,Adelanto,42208.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1600000US0600310,600310,Adin,45625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Join Demographics and income data

In [26]:
pop_data=demographic.merge(income, left_on='GEO.id', right_on='GEO.id', how='outer')
pop_data

,GEO.id,GEO.id2_x,city_x,tot_pop,male,male_pct,female,female_pct,under_5,under_5_pct,...,city_y,median_income,insurance,insurance_pct,private_insure,private_insure_pct,public_insure,public_insure_pct,no_insurance,no_insurance_pct
0,1600000US0600135,600135,Acalanes Ridge,1431,705,49.3,726,50.7,126,8.8,...,Acalanes Ridge,138672.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1600000US0600156,600156,Acampo,387,263,68.0,124,32.0,55,14.2,...,Acampo,121455.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1600000US0600212,600212,Acton,7138,3596,50.4,3542,49.6,488,6.8,...,Acton,87896.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1600000US0600296,600296,Adelanto,30670,16740,54.6,13930,45.4,3364,11.0,...,Adelanto,42208.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1600000US0600310,600310,Adin,418,211,50.5,207,49.5,21,5.0,...,Adin,45625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1600000US0600394,600394,Agoura Hills,20353,10515,51.7,9838,48.3,749,3.7,...,Agoura Hills,108820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1600000US0600450,600450,Agua Dulce,2991,1388,46.4,1603,53.6,86,2.9,...,Agua Dulce,97000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1600000US0600464,600464,Aguanga,1540,750,48.7,790,51.3,14,0.9,...,Aguanga,47754.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1600000US0600478,600478,Ahwahnee,1685,795,47.2,890,52.8,0,0.0,...,Ahwahnee,48289.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1600000US0600535,600535,Airport,1490,827,55.5,663,44.5,115,7.7,...,Airport,18779.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1600000US0600562,600562,Alameda,73239,35212,48.1,38027,51.9,4119,5.6,...,Alameda,75832.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1600000US0600618,600618,Alamo,15531,7683,49.5,7848,50.5,646,4.2,...,Alamo,149601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1600000US0600674,600674,Albany,18217,8731,47.9,9486,52.1,1437,7.9,...,Albany,72479.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1600000US0600716,600716,Albion,255,162,63.5,93,36.5,0,0.0,...,Albion,30331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1600000US0600786,600786,Alderpoint,113,59,52.2,54,47.8,6,5.3,...,Alderpoint,31000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1600000US0600884,600884,Alhambra,83301,39799,47.8,43502,52.2,4101,4.9,...,Alhambra,52717.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1600000US0600898,600898,Alhambra Valley,910,521,57.3,389,42.7,40,4.4,...,Alhambra Valley,124547.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1600000US0600947,600947,Aliso Viejo,47037,22226,47.3,24811,52.7,3983,8.5,...,Aliso Viejo,99095.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1600000US0600982,600982,Alleghany,65,49,75.4,16,24.6,0,0.0,...,Alleghany,30278.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1600000US0600996,600996,Allendale,1968,1024,52.0,944,48.0,39,2.0,...,Allendale,112837.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1600000US0601010,601010,Allensworth,281,133,47.3,148,52.7,15,5.3,...,Allensworth,24375.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1600000US0601094,601094,Almanor,10,10,100.0,0,0.0,0,0.0,...,Almanor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1600000US0601150,601150,Alondra Park,8358,4120,49.3,4238,50.7,769,9.2,...,Alondra Park,58906.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1600000US0601164,601164,Alpaugh,847,406,47.9,441,52.1,159,18.8,...,Alpaugh,22875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1600000US0601192,601192,Alpine,13332,6536,49.0,6796,51.0,593,4.4,...,Alpine,76663.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1600000US0601228,601228,Alpine Village,180,110,61.1,70,38.9,36,20.0,...,Alpine Village,56964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1600000US0601276,601276,Alta,549,273,49.7,276,50.3,6,1.1,...,Alta,56250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1600000US0601290,601290,Altadena,45006,21920,48.7,23086,51.3,2872,6.4,...,Altadena,84413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1600000US0601360,601360,Alta Sierra,6888,3151,45.7,3737,54.3,201,2.9,...,Alta Sierra,69539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1600000US0601416,601416,Alto,741,335,45.2,406,54.8,35,4.7,...,Alto,78426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1493,1600000US0685866,685866,Wilsonia,0,0,NaN,0,NaN,0,NaN,...,Wilsonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1494,1600000US0685880,685880,Wilton,4364,2217,50.8,2147,49.2,190,4.4,...,Wilton,87000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1495,1600000US0685894,685894,Winchester,2955,1470,49.7,1485,50.3,121,4.1,...,Winchester,69798.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1496,1600000US0685922,685922,Windsor,26229,12439,47.4,13790,52.6,1496,5.7,...,Windsor,77157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1497,1600000US0685992,685992,Winter Gardens,20143,9582,47.6,10561,52.4,1502,7.5,...,Winter Gardens,61084.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1498,1600000US0686020,686020,Winterhaven,493,183,37.1,310,62.9,146,29.6,...,Winterhaven,35074.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1499,1600000US0686034,686034,Winters,6616,3259,49.3,3357,50.7,585,8.8,...,Winters,59559.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1500,1600000US0686076,686076,Winton,11742,6145,52.3,5597,47.7,993,8.5,...,Winton,31022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1501,1600000US0686174,686174,Wofford Heights,2284,1175,51.4,1109,48.6,227,9.9,...,Wofford Heights,29821.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1502,1600000US0686216,686216,Woodacre,1470,751,51.1,719,48.9,52,3.5,...,Woodacre,72266.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1503,1600000US0686230,686230,Woodbridge,4153,2071,49.9,2082,50.1,182,4.4,...,Woodbridge,65867.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1504,1600000US0686244,686244,Woodcrest,14519,7173,49.4,7346,50.6,942,6.5,...,Woodcrest,91864.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1505,1600000US0686300,686300,Woodlake,7252,3816,52.6,3436,47.4,754,10.4,...,Woodlake,32013.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1506,1600000US0686328,686328,Woodland,55229,27390,49.6,27839,50.4,4252,7.7,...,Woodland,56859.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1507,1600000US0686380,686380,Woodlands,417,224,53.7,193,46.3,0,0.0,...,Woodlands,96250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1508,1600000US0686440,686440,Woodside,5263,2629,50.0,2634,50.0,194,3.7,...,Woodside,222986.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1509,1600000US0686482,686482,Woodville,1992,1020,51.2,972,48.8,223,11.2,...,Woodville,31792.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1510,1600000US0686594,686594,Wrightwood,4556,2252,49.4,2304,50.6,388,8.5,...,Wrightwood,80793.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1511,1600000US0686678,686678,Yankee Hill,240,126,52.5,114,47.5,0,0.0,...,Yankee Hill,22054.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1512,1600000US0686734,686734,Yettem,279,124,44.4,155,55.6,31,11.1,...,Yettem,24917.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1513,1600000US0686804,686804,Yolo,335,227,67.8,108,32.2,18,5.4,...,Yolo,28929.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1514,1600000US0686832,686832,Yorba Linda,63578,31580,49.7,31998,50.3,3500,5.5,...,Yorba Linda,115291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1515,1600000US0686878,686878,Yosemite Lakes,4655,2492,53.5,2163,46.5,298,6.4,...,Yosemite Lakes,77214.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1516,1600000US0686912,686912,Yosemite Valley,779,577,74.1,202,25.9,0,0.0,...,Yosemite Valley,62321.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1517,1600000US0686930,686930,Yountville,2943,1443,49.0,1500,51.0,58,2.0,...,Yountville,68368.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1518,1600000US0686944,686944,Yreka,7696,3667,47.6,4029,52.4,528,6.9,...,Yreka,31151.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1519,1600000US0686972,686972,Yuba City,64224,31826,49.6,32398,50.4,5119,8.0,...,Yuba City,48830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1520,1600000US0687042,687042,Yucaipa,50862,25823,50.8,25039,49.2,2797,5.5,...,Yucaipa,59596.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1521,1600000US0687056,687056,Yucca Valley,20508,9906,48.3,10602,51.7,1310,6.4,...,Yucca Valley,45502.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1522,1600000US0687090,687090,Zayante,781,344,44.0,437,56.0,37,4.7,...,Zayante,64028.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
list(pop_data.columns.values)

['GEO.id',
 'GEO.id2_x',
 'city_x',
 'tot_pop',
 'male',
 'male_pct',
 'female',
 'female_pct',
 'under_5',
 'under_5_pct',
 '5_9',
 '5_9_pct',
 '10_14',
 '10_14_pct',
 '15_19',
 '15_19_pct',
 '20_24',
 '20_24_pct',
 '25_34',
 '25_34_pct',
 '35_44',
 '35_44_pct',
 '45_54',
 '45_54_pct',
 '55_59',
 '55_59_pct',
 '60_64',
 '60_64_pct',
 '65_74',
 '65_74_pct',
 '75_84',
 '75_84_pct',
 '85_over',
 '85_over_pct',
 'median_age',
 'median_age_pct',
 'hispanic_latino',
 'hispanic_latino_pct',
 'mexican',
 'mexican_pct',
 'white',
 'white_pct',
 'black',
 'black_pct',
 'aian',
 'aian_pct',
 'asian',
 'asian_pct',
 'nhopi',
 'nhopi_pct',
 'other',
 'other_pct',
 'GEO.id2_y',
 'city_y',
 'median_income',
 'insurance',
 'insurance_pct',
 'private_insure',
 'private_insure_pct',
 'public_insure',
 'public_insure_pct',
 'no_insurance',
 'no_insurance_pct']

In [28]:
pop_data=pop_data.drop(columns=['GEO.id2_y','city_y'])

In [29]:
pop_data=pop_data.rename(columns={'GEO.id': 'geoid',
                         'GEO.id2_x': 'geoid2',
                         'city_x': 'city'})

In [30]:
# Fix City naming to be similar for special characters
pop_data.loc[pop_data.city=='La CaÃ±ada Flintridge', 'city']='La Canada Flintridge'
pop_data.loc[pop_data.city=='PiÃ±on Hills', 'city']='Pinon Hills'

# Change census cities names that are present in multiple places to match vaccine data city
pop_data.loc[pop_data.city=='El Sobrante Cdp (Contra Costa County), California', 'city']='El Sobrante (Contra Costa County)'
pop_data.loc[pop_data.city=='Edwards Afb', 'city']='Edwards AFB'
pop_data.loc[pop_data.city=='Beale Afb', 'city']='Beale AFB'
pop_data.loc[pop_data.city=='Las Flores Cdp (Orange County), California', 'city']='Las Flores (Orange County)'
pop_data.loc[pop_data.city=='West Whittier-Los Nietos CDP, California', 'city']='Los Nietos'
pop_data.loc[pop_data.city=="El Paso de Robles (Paso Robles)", 'city']='Paso Robles'
pop_data.loc[pop_data.city=='San Miguel Cdp (San Luis Obispo County), California', 'city']='San Miguel'
pop_data.loc[pop_data.city=='Spring Valley Cdp (San Diego County), California', 'city']='Spring Valley'

In [31]:
# Exported merged census data
pop_data.to_csv("pop_data11.csv", index=False)